package asm

import (
	"flag"
	"io/ioutil"
	"log"
	"path/filepath"
	"testing"

	"github.com/mewkiz/pkg/diffutil"
	"github.com/mewkiz/pkg/osutil"
)

// words specifies whether to colour words in diff output.
var words bool

func init() {
	flag.BoolVar(&words, "words", false, "colour words in diff output")
	flag.Parse()
}

func TestParseFile(t *testing.T) {
	golden := []struct {
		path string
	}{
		{path: "testdata/hexfloat.ll"},
		{path: "testdata/inst_aggregate.ll"},
		{path: "testdata/inst_binary.ll"},
		{path: "testdata/inst_bitwise.ll"},
		{path: "testdata/inst_conversion.ll"},
		{path: "testdata/inst_memory.ll"},
		{path: "testdata/inst_other.ll"},
		{path: "testdata/inst_vector.ll"},
		{path: "testdata/terminator.ll"},

		// DIExpression used in named metdata definition.
		{path: "testdata/diexpression.ll"},

		// Floating-point test cases (issue #31).
		{path: "../testdata/llvm/test/Analysis/CostModel/AMDGPU/fdiv.ll"},

		// float infinity.
		// TODO: fix handling of float infinity hex representation.
		//{path: "../testdata/llvm/test/Assembler/2002-04-07-InfConstant.ll"},

		// Distinguish named from unnamed locals (issue #39).
		{path: "../testdata/llvm/test/Analysis/DominanceFrontier/new_pm_test.ll"},

		// Empty array constant.
		{path: "../testdata/llvm/test/Assembler/aggregate-constant-values.ll"},

		// gep with vector indices.
		{path: "../testdata/llvm/test/Assembler/ConstantExprFold.ll"},
		{path: "../testdata/llvm/test/Assembler/getelementptr.ll"},

		// Large values in metadata.
		{path: "../testdata/llvm/test/Assembler/ditype-large-values.ll"},

		// fadd, fmul and fcmp constant expressions.
		{path: "../testdata/llvm/test/DebugInfo/ARM/selectiondag-deadcode.ll.golden"},

		// fsub constant expressions.
		{path: "../testdata/llvm/test/Transforms/InstCombine/fma.ll.golden"},

		// Constant expressions.
		{path: "../testdata/llvm/test/Transforms/ConstProp/constant-expr.ll.golden"},

		/*
			// LLVM test/Features.
			{path: "../testdata/llvm/test/Feature/OperandBundles/adce.ll"},
			{path: "../testdata/llvm/test/Feature/OperandBundles/basic-aa-argmemonly.ll"},
			{path: "../testdata/llvm/test/Feature/OperandBundles/dse.ll"},
			{path: "../testdata/llvm/test/Feature/OperandBundles/early-cse.ll"},
			{path: "../testdata/llvm/test/Feature/OperandBundles/function-attrs.ll"},
			{path: "../testdata/llvm/test/Feature/OperandBundles/inliner-conservative.ll"},
			{path: "../testdata/llvm/test/Feature/OperandBundles/merge-func.ll"},
			{path: "../testdata/llvm/test/Feature/OperandBundles/pr26510.ll"},
			{path: "../testdata/llvm/test/Feature/OperandBundles/special-state.ll"},
			//{path: "../testdata/llvm/test/Feature/alias2.ll"}, // TODO: fix grammar. syntax error at line 12. The issue is that the aliasee (a bitcast expression in this case is missing a type (in this case, the type should be i16*). `@a1 = alias i16, bitcast (i32* @v1 to i16*)`
			//{path: "../testdata/llvm/test/Feature/aliases.ll"}, // TODO: fix grammar. syntax error at line 29. The issue is that the aliasee (a bitcast expression in this case is missing a type (in this case, the type should be i64*). `@A = alias i64, bitcast (i32* @bar to i64*)`
			//{path: "../testdata/llvm/test/Feature/alignment.ll"}, // TODO: fix grammar. syntax error at line 7. The issue is that there is a parsing ambiguity between GlobalAttr and FuncAttr, both of which may be empty and both of which may contain Align.
			{path: "../testdata/llvm/test/Feature/attributes.ll"},
			{path: "../testdata/llvm/test/Feature/basictest.ll"},
			{path: "../testdata/llvm/test/Feature/callingconventions.ll"},
			{path: "../testdata/llvm/test/Feature/calltest.ll"},
			{path: "../testdata/llvm/test/Feature/casttest.ll"},
			{path: "../testdata/llvm/test/Feature/cfgstructures.ll"},
			{path: "../testdata/llvm/test/Feature/cold.ll"},
			{path: "../testdata/llvm/test/Feature/comdat.ll"},
			//{path: "../testdata/llvm/test/Feature/constexpr.ll"}, // TODO: re-enable when signed hex integer literals are supported.
			{path: "../testdata/llvm/test/Feature/constpointer.ll"},
			{path: "../testdata/llvm/test/Feature/const_pv.ll"},
			{path: "../testdata/llvm/test/Feature/elf-linker-options.ll"},
			{path: "../testdata/llvm/test/Feature/escaped_label.ll"},
			{path: "../testdata/llvm/test/Feature/exception.ll"},
			{path: "../testdata/llvm/test/Feature/float.ll"},
			{path: "../testdata/llvm/test/Feature/fold-fpcast.ll"},
			{path: "../testdata/llvm/test/Feature/forwardreftest.ll"},
			{path: "../testdata/llvm/test/Feature/fp-intrinsics.ll"},
			{path: "../testdata/llvm/test/Feature/global_pv.ll"},
			//{path: "../testdata/llvm/test/Feature/globalredefinition3.ll"}, // TODO: figure out how to test. should report error "redefinition of global '@B'"
			{path: "../testdata/llvm/test/Feature/global_section.ll"},
			{path: "../testdata/llvm/test/Feature/globalvars.ll"},
			{path: "../testdata/llvm/test/Feature/indirectcall2.ll"},
			{path: "../testdata/llvm/test/Feature/indirectcall.ll"},
			{path: "../testdata/llvm/test/Feature/inlineasm.ll"},
			{path: "../testdata/llvm/test/Feature/instructions.ll"},
			{path: "../testdata/llvm/test/Feature/intrinsic-noduplicate.ll"},
			{path: "../testdata/llvm/test/Feature/intrinsics.ll"},
			{path: "../testdata/llvm/test/Feature/load_module.ll"},
			{path: "../testdata/llvm/test/Feature/md_on_instruction.ll"},
			{path: "../testdata/llvm/test/Feature/memorymarkers.ll"},
			{path: "../testdata/llvm/test/Feature/metadata.ll"},
			{path: "../testdata/llvm/test/Feature/minsize_attr.ll"},
			{path: "../testdata/llvm/test/Feature/NamedMDNode2.ll"},
			{path: "../testdata/llvm/test/Feature/NamedMDNode.ll"},
			{path: "../testdata/llvm/test/Feature/newcasts.ll"},
			{path: "../testdata/llvm/test/Feature/optnone.ll"},
			{path: "../testdata/llvm/test/Feature/optnone-llc.ll"},
			{path: "../testdata/llvm/test/Feature/optnone-opt.ll"},
			{path: "../testdata/llvm/test/Feature/packed.ll"},
			{path: "../testdata/llvm/test/Feature/packed_struct.ll"},
			{path: "../testdata/llvm/test/Feature/paramattrs.ll"},
			{path: "../testdata/llvm/test/Feature/ppcld.ll"},
			{path: "../testdata/llvm/test/Feature/prefixdata.ll"},
			{path: "../testdata/llvm/test/Feature/prologuedata.ll"},
			{path: "../testdata/llvm/test/Feature/properties.ll"},
			{path: "../testdata/llvm/test/Feature/prototype.ll"},
			{path: "../testdata/llvm/test/Feature/recursivetype.ll"},
			{path: "../testdata/llvm/test/Feature/seh-nounwind.ll"},
			{path: "../testdata/llvm/test/Feature/simplecalltest.ll"},
			{path: "../testdata/llvm/test/Feature/smallest.ll"},
			{path: "../testdata/llvm/test/Feature/small.ll"},
			{path: "../testdata/llvm/test/Feature/sparcld.ll"},
			{path: "../testdata/llvm/test/Feature/strip_names.ll"},
			{path: "../testdata/llvm/test/Feature/terminators.ll"},
			{path: "../testdata/llvm/test/Feature/testalloca.ll"},
			{path: "../testdata/llvm/test/Feature/testconstants.ll"},
			{path: "../testdata/llvm/test/Feature/testlogical.ll"},
			//{path: "../testdata/llvm/test/Feature/testtype.ll"}, // TODO: fix nil pointer dereference
			{path: "../testdata/llvm/test/Feature/testvarargs.ll"},
			{path: "../testdata/llvm/test/Feature/undefined.ll"},
			{path: "../testdata/llvm/test/Feature/unreachable.ll"},
			{path: "../testdata/llvm/test/Feature/varargs.ll"},
			{path: "../testdata/llvm/test/Feature/varargs_new.ll"},
			{path: "../testdata/llvm/test/Feature/vector-cast-constant-exprs.ll"},
			{path: "../testdata/llvm/test/Feature/weak_constant.ll"},
			{path: "../testdata/llvm/test/Feature/weirdnames.ll"},
			{path: "../testdata/llvm/test/Feature/x86ld.ll"},

			// LLVM test/Assembler.
			{path: "../testdata/llvm/test/Assembler/2002-03-08-NameCollision.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-03-08-NameCollision2.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-04-07-HexFloatConstants.ll"},
			//{path: "../testdata/llvm/test/Assembler/2002-04-07-InfConstant.ll"}, // handled above.
			{path: "../testdata/llvm/test/Assembler/2002-04-29-NameBinding.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-05-02-InvalidForwardRef.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-07-14-OpaqueType.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-07-25-QuoteInString.ll"},
			// TODO: figure out how function return type should be printed in call instructions.
			//{path: "../testdata/llvm/test/Assembler/2002-07-25-ReturnPtrFunction.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-07-31-SlashInString.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-08-15-CastAmbiguity.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-08-15-ConstantExprProblem.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-08-15-UnresolvedGlobalReference.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-08-16-ConstExprInlined.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-08-19-BytecodeReader.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-08-22-DominanceProblem.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-10-08-LargeArrayPerformance.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-10-13-ConstantEncodingProblem.ll"},
			{path: "../testdata/llvm/test/Assembler/2002-12-15-GlobalResolve.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-01-30-UnsignedString.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-04-15-ConstantInitAssertion.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-04-25-UnresolvedGlobalReference.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-05-03-BytecodeReaderProblem.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-05-12-MinIntProblem.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-05-15-AssemblerProblem.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-05-15-SwitchBug.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-05-21-ConstantShiftExpr.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-05-21-EmptyStructTest.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-05-21-MalformedShiftCrash.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-05-21-MalformedStructCrash.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-08-20-ConstantExprGEP-Fold.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-08-21-ConstantExprCast-Fold.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-11-05-ConstantExprShift.ll"},
			{path: "../testdata/llvm/test/Assembler/2003-11-12-ConstantExprCast.ll"},
			{path: "../testdata/llvm/test/Assembler/2004-01-11-getelementptrfolding.ll"},
			{path: "../testdata/llvm/test/Assembler/2004-01-20-MaxLongLong.ll"},
			{path: "../testdata/llvm/test/Assembler/2004-02-01-NegativeZero.ll"},
			{path: "../testdata/llvm/test/Assembler/2004-02-27-SelfUseAssertError.ll"},
			{path: "../testdata/llvm/test/Assembler/2004-03-07-FunctionAddressAlignment.ll"},
			{path: "../testdata/llvm/test/Assembler/2004-04-04-GetElementPtrIndexTypes.ll"},
			{path: "../testdata/llvm/test/Assembler/2004-06-07-VerifierBug.ll"},
			{path: "../testdata/llvm/test/Assembler/2004-10-22-BCWriterUndefBug.ll"},
			{path: "../testdata/llvm/test/Assembler/2005-01-03-FPConstantDisassembly.ll"},
			{path: "../testdata/llvm/test/Assembler/2005-01-31-CallingAggregateFunction.ll"},
			{path: "../testdata/llvm/test/Assembler/2005-05-05-OpaqueUndefValues.ll"},
			{path: "../testdata/llvm/test/Assembler/2005-12-21-ZeroInitVector.ll"},
			{path: "../testdata/llvm/test/Assembler/2006-12-09-Cast-To-Bool.ll"},
			{path: "../testdata/llvm/test/Assembler/2007-01-05-Cmp-ConstExpr.ll"},
			{path: "../testdata/llvm/test/Assembler/2007-01-16-CrashOnBadCast.ll"},
			{path: "../testdata/llvm/test/Assembler/2007-01-16-CrashOnBadCast2.ll"},
			// TODO: fix type checking during translation of local variables.
			//{path: "../testdata/llvm/test/Assembler/2007-03-18-InvalidNumberedVar.ll"},
			{path: "../testdata/llvm/test/Assembler/2007-03-19-NegValue.ll"},
			{path: "../testdata/llvm/test/Assembler/2007-04-20-AlignedLoad.ll"},
			{path: "../testdata/llvm/test/Assembler/2007-04-20-AlignedStore.ll"},
			{path: "../testdata/llvm/test/Assembler/2007-04-25-AssemblerFoldExternWeak.ll"},
			{path: "../testdata/llvm/test/Assembler/2007-05-21-Escape.ll"},
			{path: "../testdata/llvm/test/Assembler/2007-07-19-ParamAttrAmbiguity.ll"},
			{path: "../testdata/llvm/test/Assembler/2007-09-10-AliasFwdRef.ll"},
			{path: "../testdata/llvm/test/Assembler/2007-09-29-GC.ll"},
			// TODO: fix translation of pointer with address space to pointer with address space; e.g. i32 addrspace(33)* addrspace(44)*
			//{path: "../testdata/llvm/test/Assembler/2007-12-11-AddressSpaces.ll"},
			{path: "../testdata/llvm/test/Assembler/2008-01-11-VarargAttrs.ll"},
			{path: "../testdata/llvm/test/Assembler/2008-07-10-APInt.ll"},
			{path: "../testdata/llvm/test/Assembler/2008-09-02-FunctionNotes.ll"},
			{path: "../testdata/llvm/test/Assembler/2008-09-02-FunctionNotes2.ll"},
			{path: "../testdata/llvm/test/Assembler/2008-09-29-RetAttr.ll"},
			{path: "../testdata/llvm/test/Assembler/2008-10-14-QuoteInName.ll"},
			{path: "../testdata/llvm/test/Assembler/2009-02-01-UnnamedForwardRef.ll"},
			{path: "../testdata/llvm/test/Assembler/2009-02-28-CastOpc.ll"},
			{path: "../testdata/llvm/test/Assembler/2009-02-28-StripOpaqueName.ll"},
			{path: "../testdata/llvm/test/Assembler/2009-03-24-ZextConstantExpr.ll"},
			{path: "../testdata/llvm/test/Assembler/2009-07-24-ZeroArgGEP.ll"},
			{path: "../testdata/llvm/test/Assembler/2010-02-05-FunctionLocalMetadataBecomesNull.ll"},
			{path: "../testdata/llvm/test/Assembler/addrspacecast-alias.ll"},
			//{path: "../testdata/llvm/test/Assembler/aggregate-constant-values.ll"}, // tested above.
			{path: "../testdata/llvm/test/Assembler/aggregate-return-single-value.ll"},
			{path: "../testdata/llvm/test/Assembler/alias-use-list-order.ll"},
			{path: "../testdata/llvm/test/Assembler/align-inst-alloca.ll"},
			{path: "../testdata/llvm/test/Assembler/align-inst.ll"},
			{path: "../testdata/llvm/test/Assembler/alignstack.ll"},
			{path: "../testdata/llvm/test/Assembler/alloca-addrspace-elems.ll"},
			{path: "../testdata/llvm/test/Assembler/alloca-addrspace0.ll"},
			{path: "../testdata/llvm/test/Assembler/alloca-invalid-type-2.ll"},
			{path: "../testdata/llvm/test/Assembler/alloca-size-one.ll"},
			{path: "../testdata/llvm/test/Assembler/anon-functions.ll"},
			{path: "../testdata/llvm/test/Assembler/atomic.ll"},
			{path: "../testdata/llvm/test/Assembler/attribute-builtin.ll"},
			{path: "../testdata/llvm/test/Assembler/auto_upgrade_intrinsics.ll"},
			{path: "../testdata/llvm/test/Assembler/auto_upgrade_nvvm_intrinsics.ll"},
			{path: "../testdata/llvm/test/Assembler/autoupgrade-thread-pointer.ll"},
			{path: "../testdata/llvm/test/Assembler/bcwrap.ll"},
			{path: "../testdata/llvm/test/Assembler/call-nonzero-program-addrspace-2.ll"},
			{path: "../testdata/llvm/test/Assembler/call-nonzero-program-addrspace.ll"},
			{path: "../testdata/llvm/test/Assembler/comment.ll"},
			//{path: "../testdata/llvm/test/Assembler/ConstantExprFold.ll"}, // tested above.
			{path: "../testdata/llvm/test/Assembler/ConstantExprFoldCast.ll"},
			{path: "../testdata/llvm/test/Assembler/ConstantExprFoldSelect.ll"},
			{path: "../testdata/llvm/test/Assembler/ConstantExprNoFold.ll"},
			{path: "../testdata/llvm/test/Assembler/datalayout-alloca-addrspace-mismatch-0.ll"},
			{path: "../testdata/llvm/test/Assembler/datalayout-alloca-addrspace-mismatch-1.ll"},
			{path: "../testdata/llvm/test/Assembler/datalayout-alloca-addrspace-mismatch-2.ll"},
			{path: "../testdata/llvm/test/Assembler/datalayout-alloca-addrspace.ll"},
			{path: "../testdata/llvm/test/Assembler/datalayout-program-addrspace.ll"},
			{path: "../testdata/llvm/test/Assembler/debug-info.ll"},
			{path: "../testdata/llvm/test/Assembler/debug-label-bitcode.ll"},
			{path: "../testdata/llvm/test/Assembler/dicompileunit.ll"},
			{path: "../testdata/llvm/test/Assembler/dicompositetype-members.ll"},
			{path: "../testdata/llvm/test/Assembler/DIEnumerator.ll"},
			{path: "../testdata/llvm/test/Assembler/diexpression.ll"},
			{path: "../testdata/llvm/test/Assembler/difile-escaped-chars.ll"},
			{path: "../testdata/llvm/test/Assembler/diglobalvariable.ll"},
			{path: "../testdata/llvm/test/Assembler/DIGlobalVariableExpression.ll"},
			{path: "../testdata/llvm/test/Assembler/diimportedentity.ll"},
			{path: "../testdata/llvm/test/Assembler/dilexicalblock.ll"},
			{path: "../testdata/llvm/test/Assembler/dilocalvariable-arg-large.ll"},
			{path: "../testdata/llvm/test/Assembler/dilocalvariable.ll"},
			{path: "../testdata/llvm/test/Assembler/dilocation.ll"},
			{path: "../testdata/llvm/test/Assembler/DIMacroFile.ll"},
			{path: "../testdata/llvm/test/Assembler/dimodule.ll"},
			{path: "../testdata/llvm/test/Assembler/dinamespace.ll"},
			{path: "../testdata/llvm/test/Assembler/diobjcproperty.ll"},
			{path: "../testdata/llvm/test/Assembler/distinct-mdnode.ll"},
			{path: "../testdata/llvm/test/Assembler/disubprogram.ll"},
			{path: "../testdata/llvm/test/Assembler/disubrange-empty-array.ll"},
			{path: "../testdata/llvm/test/Assembler/disubroutinetype.ll"},
			{path: "../testdata/llvm/test/Assembler/ditemplateparameter.ll"},
			//{path: "../testdata/llvm/test/Assembler/ditype-large-values.ll"}, // tested above.
			{path: "../testdata/llvm/test/Assembler/dllimport-dsolocal-diag.ll"},
			{path: "../testdata/llvm/test/Assembler/drop-debug-info-nonzero-alloca.ll"},
			{path: "../testdata/llvm/test/Assembler/drop-debug-info.ll"},
			{path: "../testdata/llvm/test/Assembler/externally-initialized.ll"},
			{path: "../testdata/llvm/test/Assembler/extractvalue-invalid-idx.ll"},
			{path: "../testdata/llvm/test/Assembler/fast-math-flags.ll"},
			{path: "../testdata/llvm/test/Assembler/flags.ll"},
			{path: "../testdata/llvm/test/Assembler/generic-debug-node.ll"},
			// TODO: investigate why we are able to parse `return i32* %gep`, should not be possible as there is no `return` token in the grammar.
			//{path: "../testdata/llvm/test/Assembler/getelementptr_invalid_ptr.ll"},
			{path: "../testdata/llvm/test/Assembler/getelementptr_struct.ll"},
			// TODO: fix computation of gep type. We currently do not update the return type to vector if the first gep index is a scalar, but the second (or later) indices is a vector. As such, we currently compute the type `i32*` where `<4 x i32*>` should have been computed.
			//{path: "../testdata/llvm/test/Assembler/getelementptr_vec_ce.ll"},
			// TODO: fix computation of gep type. We currently do not update the return type to vector if the first gep index is a scalar, but the second (or later) indices is a vector. As such, we currently compute the type `i32*` where `<4 x i32*>` should have been computed.
			//{path: "../testdata/llvm/test/Assembler/getelementptr_vec_ce2.ll"},
			// TODO: fix gep type computation.
			//{path: "../testdata/llvm/test/Assembler/getelementptr_vec_idx1.ll"},
			// TODO: fix gep type computation.
			//{path: "../testdata/llvm/test/Assembler/getelementptr_vec_idx2.ll"},
			// TODO: fix gep type computation.
			//{path: "../testdata/llvm/test/Assembler/getelementptr_vec_idx3.ll"},
			{path: "../testdata/llvm/test/Assembler/getelementptr_vec_idx4.ll"},
			//{path: "../testdata/llvm/test/Assembler/getelementptr.ll"}, // tested above.
			{path: "../testdata/llvm/test/Assembler/getInt.ll"},
			{path: "../testdata/llvm/test/Assembler/global-addrspace-forwardref.ll"},
			{path: "../testdata/llvm/test/Assembler/globalvariable-attributes.ll"},
			{path: "../testdata/llvm/test/Assembler/gv-invalid-type.ll"},
			{path: "../testdata/llvm/test/Assembler/half-constprop.ll"},
			{path: "../testdata/llvm/test/Assembler/half-conv.ll"},
			{path: "../testdata/llvm/test/Assembler/half.ll"},
			{path: "../testdata/llvm/test/Assembler/huge-array.ll"},
			{path: "../testdata/llvm/test/Assembler/ifunc-asm.ll"},
			{path: "../testdata/llvm/test/Assembler/ifunc-dsolocal.ll"},
			{path: "../testdata/llvm/test/Assembler/ifunc-use-list-order.ll"},
			{path: "../testdata/llvm/test/Assembler/inalloca.ll"},
			{path: "../testdata/llvm/test/Assembler/incorrect-tdep-attrs-parsing.ll"},
			{path: "../testdata/llvm/test/Assembler/inline-asm-clobber.ll"},
			{path: "../testdata/llvm/test/Assembler/insertextractvalue.ll"},
			{path: "../testdata/llvm/test/Assembler/insertvalue-invalid-idx.ll"},
			// TODO: check result type of insertvalue during translation.
			//{path: "../testdata/llvm/test/Assembler/insertvalue-invalid-type-1.ll"},
			{path: "../testdata/llvm/test/Assembler/insertvalue-invalid-type.ll"},
			{path: "../testdata/llvm/test/Assembler/internal-hidden-alias.ll"},
			{path: "../testdata/llvm/test/Assembler/internal-hidden-function.ll"},
			{path: "../testdata/llvm/test/Assembler/internal-hidden-variable.ll"},
			{path: "../testdata/llvm/test/Assembler/internal-protected-alias.ll"},
			{path: "../testdata/llvm/test/Assembler/internal-protected-function.ll"},
			{path: "../testdata/llvm/test/Assembler/internal-protected-variable.ll"},
			// Skip test cases with invalid input for now.
			//{path: "../testdata/llvm/test/Assembler/invalid_cast.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid_cast2.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid_cast3.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid_cast4.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-alias-mismatched-explicit-type.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout-alloca-addrspace.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout-program-addrspace.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout1.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout10.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout11.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout12.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout13.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout14.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout15.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout16.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout17.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout18.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout19.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout2.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout20.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout21.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout22.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout23.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout24.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout3.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout4.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout5.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout6.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout7.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout8.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-datalayout9.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-debug-info-version.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dicompileunit-emissionkind-bad.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dicompileunit-language-overflow.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dicompileunit-missing-language.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dicompileunit-null-file.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dicompileunit-uniqued.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dicompositetype-missing-tag.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-diderivedtype-missing-basetype.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-diderivedtype-missing-tag.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dienumerator-missing-name.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dienumerator-missing-value.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-diexpression-verify.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-difile-missing-directory.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-difile-missing-filename.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-diglobalvariable-empty-name.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-diglobalvariable-missing-name.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-diimportedentity-missing-scope.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilexicalblock-missing-scope.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilexicalblock-null-scope.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilexicalblockfile-missing-discriminator.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilexicalblockfile-missing-scope.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilexicalblockfile-null-scope.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilocalvariable-arg-large.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilocalvariable-missing-scope.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilocalvariable-null-scope.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilocation-field-twice.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilocation-missing-scope-2.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilocation-missing-scope.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilocation-null-scope.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilocation-overflow-column.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dilocation-overflow-line.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-dinamespace-missing-namespace.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-disubprogram-uniqued-definition.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-disubrange-count-missing.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-disubrange-count-node.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-disubroutinetype-missing-types.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-ditemplatetypeparameter-missing-type.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-ditemplatevalueparameter-missing-value.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-fwdref2.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-generic-debug-node-tag-missing.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-generic-debug-node-tag-overflow.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-gep-mismatched-explicit-type.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-hexint.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-inttype.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-load-mismatched-explicit-type.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-name.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-name2.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-uselistorder_bb-numbered.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-uselistorder-indexes-duplicated.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-uselistorder-indexes-empty.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-uselistorder-indexes-one.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-uselistorder-indexes-ordered.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-uselistorder-indexes-range.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-uselistorder-indexes-toofew.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-uselistorder-indexes-toomany.ll"},
			//{path: "../testdata/llvm/test/Assembler/invalid-uselistorder-type.ll"},
			{path: "../testdata/llvm/test/Assembler/invoke-nonzero-program-addrspace.ll"},
			{path: "../testdata/llvm/test/Assembler/large-comdat.ll"},
			{path: "../testdata/llvm/test/Assembler/local-unnamed-addr.ll"},
			{path: "../testdata/llvm/test/Assembler/max-inttype.ll"},
			{path: "../testdata/llvm/test/Assembler/metadata-decl.ll"},
			{path: "../testdata/llvm/test/Assembler/metadata-function-local.ll"},
			{path: "../testdata/llvm/test/Assembler/metadata-null-operands.ll"},
			{path: "../testdata/llvm/test/Assembler/metadata.ll"},
			{path: "../testdata/llvm/test/Assembler/MultipleReturnValueType.ll"},
			{path: "../testdata/llvm/test/Assembler/musttail-invalid-1.ll"},
			{path: "../testdata/llvm/test/Assembler/musttail-invalid-2.ll"},
			{path: "../testdata/llvm/test/Assembler/musttail.ll"},
			{path: "../testdata/llvm/test/Assembler/named-metadata.ll"},
			{path: "../testdata/llvm/test/Assembler/no-mdstring-upgrades.ll"},
			{path: "../testdata/llvm/test/Assembler/numbered-values.ll"},
			{path: "../testdata/llvm/test/Assembler/private-hidden-alias.ll"},
			{path: "../testdata/llvm/test/Assembler/private-hidden-function.ll"},
			{path: "../testdata/llvm/test/Assembler/private-hidden-variable.ll"},
			{path: "../testdata/llvm/test/Assembler/private-protected-alias.ll"},
			{path: "../testdata/llvm/test/Assembler/private-protected-function.ll"},
			{path: "../testdata/llvm/test/Assembler/private-protected-variable.ll"},
			{path: "../testdata/llvm/test/Assembler/select.ll"},
			// TODO: add support for fp128 hex literals.
			//{path: "../testdata/llvm/test/Assembler/short-hexpair.ll"},
			{path: "../testdata/llvm/test/Assembler/source-filename-backslash.ll"},
			{path: "../testdata/llvm/test/Assembler/source-filename.ll"},
			// TODO: add support for ThinLTO module summaries.
			//{path: "../testdata/llvm/test/Assembler/thinlto-summary.ll"},
			{path: "../testdata/llvm/test/Assembler/tls-models.ll"},
			{path: "../testdata/llvm/test/Assembler/token.ll"},
			{path: "../testdata/llvm/test/Assembler/unnamed-addr.ll"},
			{path: "../testdata/llvm/test/Assembler/unnamed-alias.ll"},
			{path: "../testdata/llvm/test/Assembler/unnamed.ll"},
			{path: "../testdata/llvm/test/Assembler/uselistorder_bb.ll"},
			{path: "../testdata/llvm/test/Assembler/uselistorder.ll"},
			{path: "../testdata/llvm/test/Assembler/vbool-cmp.ll"},
			{path: "../testdata/llvm/test/Assembler/vector-cmp.ll"},
			{path: "../testdata/llvm/test/Assembler/vector-select.ll"},
			{path: "../testdata/llvm/test/Assembler/vector-shift.ll"},
			{path: "../testdata/llvm/test/Assembler/x86mmx.ll"},

			// LLVM test/DebugInfo/Generic.
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2009-10-16-Phi.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2009-11-03-InsertExtractValue.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2009-11-05-DeadGlobalVariable.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2009-11-06-NamelessGlobalVariable.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2009-11-10-CurrentFn.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2010-01-05-DbgScope.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2010-03-12-llc-crash.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2010-03-19-DbgDeclare.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2010-03-24-MemberFn.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2010-04-06-NestedFnDbgInfo.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2010-04-19-FramePtr.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2010-05-03-DisableFramePtr.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2010-05-03-OriginDIE.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2010-05-10-MultipleCU.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2010-06-29-InlinedFnLocalVar.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/2010-10-01-crash.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/accel-table-hash-collisions.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/array.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/block-asan.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/bug_null_debuginfo.ll"},
			{path: "../testdata/llvm/test/DebugInfo/Generic/constant-pointers.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/containing-type-extension.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/cross-cu-inlining.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/cross-cu-linkonce-distinct.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/cross-cu-linkonce.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/cu-range-hole.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/cu-ranges.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/dbg-at-specficiation.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/dead-argument-order.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debug-info-always-inline.ll"},
			{path: "../testdata/llvm/test/DebugInfo/Generic/debug-info-enum.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debuginfofinder-forward-declaration.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debuginfofinder-imported-global-variable.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debuginfofinder-inlined-cu.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debuginfofinder-multiple-cu.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debug-info-qualifiers.ll"},
			{path: "../testdata/llvm/test/DebugInfo/Generic/debug-label-mi.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debug-label-opt.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debug-names-empty-cu.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debug-names-empty-name.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debug-names-hash-collisions.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debug-names-index-type.ll"},
			{path: "../testdata/llvm/test/DebugInfo/Generic/debug-names-linkage-name.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debug-names-many-cu.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debug-names-name-collisions.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debug-names-one-cu.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/debug-names-two-cu.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/def-line.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/discriminated-union.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/discriminator.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/disubrange_vla.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/disubrange_vla_no_dbgvalue.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/dwarf-public-names.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/empty.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/enum.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/enum-types.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/extended-loc-directive.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/global.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/global-sra-array.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/global-sra-single-member.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/global-sra-struct.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/gmlt_profiling.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/gvn.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/imported-name-inlined.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/incorrect-variable-debugloc1.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/incorrect-variable-debugloc.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/indvar-discriminator.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/inheritance.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/inlined-arguments.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/inline-debug-info.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/inline-debug-info-multiret.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/inline-debug-loc.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/inlined-strings.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/inlined-vars.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/inline-no-debug-info.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/inline-scopes.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/instcombine-phi.ll"},
			{path: "../testdata/llvm/test/DebugInfo/Generic/invalid.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/licm-hoist-debug-loc.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/linear-dbg-value.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/linkage-name-abstract.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/location-verifier.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/lto-comp-dir.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/mainsubprogram.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/member-order.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/member-pointers.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/missing-abstract-variable.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/multiline.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/namespace_function_definition.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/namespace_inline_function_definition.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/namespace.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/noscopes.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/Generic/pass-by-value.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/piece-verifier.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/PR20038.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/PR37395.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/ptrsize.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/recursive_inlining.ll"}, // TODO: fix grammar. syntax error at line 118. Issue with Align.
			//{path: "../testdata/llvm/test/DebugInfo/Generic/restrict.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/simplifycfg_sink_last_inst.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/skeletoncu.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/sroa-larger.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/sroa-samesize.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/store-tail-merge.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/string-offsets-form.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/sugared-constants.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/sunk-compare.ll"},
			{path: "../testdata/llvm/test/DebugInfo/Generic/template-recursive-void.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/thrownTypes.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/tu-composite.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/tu-member-pointer.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/two-cus-from-same-file.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/typedef.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/unconditional-branch.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/univariant-discriminated-union.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/varargs.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/version.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/virtual-index.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/Generic/volatile-alloca.ll"},

			// LLVM test/DebugInfo.
			{path: "../testdata/llvm/test/DebugInfo/check-debugify-preserves-analyses.ll"},
			{path: "../testdata/llvm/test/DebugInfo/cross-cu-scope.ll"},
			{path: "../testdata/llvm/test/DebugInfo/debugify-bogus-dbg-value.ll"},
			{path: "../testdata/llvm/test/DebugInfo/debugify-each.ll"},
			{path: "../testdata/llvm/test/DebugInfo/debugify-export.ll"},
			{path: "../testdata/llvm/test/DebugInfo/debugify.ll"},
			{path: "../testdata/llvm/test/DebugInfo/debugify-report-missing-locs-only.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/debuglineinfo-path.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			{path: "../testdata/llvm/test/DebugInfo/dwo.ll"},
			{path: "../testdata/llvm/test/DebugInfo/macro_link.ll"},
			{path: "../testdata/llvm/test/DebugInfo/omit-empty.ll"},
			{path: "../testdata/llvm/test/DebugInfo/pr34186.ll"},
			{path: "../testdata/llvm/test/DebugInfo/pr34672.ll"},
			{path: "../testdata/llvm/test/DebugInfo/skeletoncu.ll"},
			{path: "../testdata/llvm/test/DebugInfo/strip-DIGlobalVariable.ll"},
			{path: "../testdata/llvm/test/DebugInfo/strip-loop-metadata.ll"},
			{path: "../testdata/llvm/test/DebugInfo/strip-module-flags.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/unrolled-loop-remainder.ll"}, // TODO: figure out how to handle duplicate (but distinct) AttrGroupDef

			// LLVM test/DebugInfo/X86.
			//{path: "../testdata/llvm/test/DebugInfo/X86/2010-04-13-PubType.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/2011-09-26-GlobalVarContext.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/2011-12-16-BadStructRef.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/abstract_origin.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/accel-tables-dwarf5.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/accel-tables.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/align_c11.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/align_cpp11.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/aligned_stack_var.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/align_objc.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/arange-and-stub.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/arange.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/arguments.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/array2.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/array.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/atomic-c11-dwarf-4.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/atomic-c11-dwarf-5.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/bbjoin.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/bitcast-di.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/bitfields-dwarf4.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/bitfields.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/block-capture.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/byvalstruct.ll"},
			{path: "../testdata/llvm/test/DebugInfo/X86/clang-module.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/clone-module-2.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/clone-module.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/coff_debug_info_type.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/coff_relative_names.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/concrete_out_of_line.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/constant-aggregate.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/constant-loclist.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/containing-type-extension-rust.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/c-type-units.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/cu-ranges.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/cu-ranges-odr.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/data_member_location.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-abstract-vars-g-gmlt.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-addr-dse.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-addr.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-byval-parameter.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-const-int.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-const.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-declare-alloca.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-declare-arg.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-declare-inalloca.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-declare.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-file-name.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-i128-const.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-merge-loc-entry.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-prolog-end.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-subrange.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-value-const-byref.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-value-dag-combine.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg_value_direct.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-value-frame-index.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-value-g-gmlt.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-value-inlined-parameter.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-value-isel.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-value-location.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-value-range.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-value-regmask-clobber.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-value-terminator.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-value-transfer-order.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dbg-vector-size.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug_addr.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug_and_nodebug_CUs.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-dead-local-var.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug_frame.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debugger-tune.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-info-access.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-info-block-captured-self.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-info-blocks.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-info-packed-struct.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-info-producer-with-flags.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-info-static-member.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-loc-asan.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-loc-frame.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-loc-offset.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-macro.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/debug-names-split-dwarf.ll"},
			{path: "../testdata/llvm/test/DebugInfo/X86/debug-ranges-offset.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/decl-derived-member.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/default-subrange-array.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/deleted-bit-piece.ll"},
			{path: "../testdata/llvm/test/DebugInfo/X86/DIModuleContext.ll"},
			{path: "../testdata/llvm/test/DebugInfo/X86/DIModule.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/discriminator2.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/discriminator3.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/discriminator.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dllimport.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/double-declare.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dwarf-aranges.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dwarf-aranges-no-dwarf-labels.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dwarf-linkage-names.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dwarf-no-source-loc.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dwarf-public-names.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dwarf-pubnames-split.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/DW_AT_byte_size.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/DW_AT_calling-convention.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/DW_AT_linkage_name.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/DW_AT_location-reference.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/DW_AT_object_pointer.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/DW_AT_specification.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/DW_AT_stmt_list_sec_offset.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/dw_op_minus_direct.ll"},
			{path: "../testdata/llvm/test/DebugInfo/X86/dw_op_minus.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/DW_TAG_friend.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/earlydup-crash.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/elf-names.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/empty-and-one-elem-array.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/empty-array.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/empty.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/empty_macinfo.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/ending-run.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/enum-class.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/enum-fwd-decl.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/fi-expr.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/fi-piece.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/fission-cu.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/fission-hash.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/fission-inline.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/fission-no-inlining.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/fission-ranges.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/float_const.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/float_const_loclist.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/formal_parameter.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/fragment-offset-order.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/FrameIndexExprs.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/frame-register.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/generate-odr-hash.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/ghost-sdnode-dbgvalues.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/global-expression.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/global-sra-fp80-array.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/global-sra-fp80-struct.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/gnu-public-names-empty.ll"}, // TODO: fix grammar. syntax error at line 20. Issue with gnuPubnames in metadata. Should the metadata contain gnuPubnames, or is this now NameTableKind or something else?
			//{path: "../testdata/llvm/test/DebugInfo/X86/gnu-public-names-gmlt.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/gnu-public-names.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/gnu-public-names-multiple-cus.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/gnu-public-names-tu.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/header.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/inline-asm-locs.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/InlinedFnLocalVar.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/inlined-formal-parameter.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/inlined-indirect-value.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/inline-member-function.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/inline-namespace.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/inline-seldag-test.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/instcombine-instrinsics.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/invalid-prologue-end.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/isel-cse-line.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/lexical-block-file-inline.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/lexical_block.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/line-info.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/linkage-name.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/live-debug-values.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/live-debug-variables.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/live-debug-vars-keep-undef.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/low-pc-cu.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/mem2reg_fp80.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/memberfnptr.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/mi-print.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/misched-dbg-value.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/missing-file-line.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/mixed-nodebug-cu.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/multiple-aranges.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/multiple-at-const-val.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/nodebug.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/no_debug_ranges.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/nodebug_with_debug_loc.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/nondefault-subrange-array.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/nophysreg.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/no-public-sections.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/noreturn_c11.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/noreturn_cpp11.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/noreturn_objc.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/objc-fwd-decl.ll"},
			{path: "../testdata/llvm/test/DebugInfo/X86/objc-property-void.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/op_deref.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/parameters.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/partial-constant.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/pieces-1.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/pieces-2.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/pieces-3.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/pieces-4.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/pointer-type-size.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/pr11300.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/pr12831.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/pr13303.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/pr19307.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/PR26148.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/pr28270.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/pr34545.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/PR37234.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/processes-relocations.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/prologue-stack.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/range_reloc_base.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/range_reloc.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/ref_addr_relocation.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/reference-argument.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/rematerialize.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/rnglists_base_attr.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/rnglists_curanges.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/rvalue-ref.ll"},
			{path: "../testdata/llvm/test/DebugInfo/X86/safestack-byval.ll"},
			{path: "../testdata/llvm/test/DebugInfo/X86/sdag-combine.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sdag-dangling-dbgvalue.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sdag-dbgvalue-phi-use-1.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sdag-dbgvalue-phi-use-2.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sdag-dbgvalue-phi-use-3.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sdag-dbgvalue-phi-use-4.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sdag-salvage-add.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sdagsplit-1.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sdag-split-arg.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/sections_as_references.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/single-dbg_value.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/single-fi.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/spill-indirect-nrvo.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/spill-nontrivial-param.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/spill-nospill.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/split-dwarf-cross-unit-reference.ll"}, // TODO: figure out how to handle AttrGroupID with missing AttrGroupDef
			//{path: "../testdata/llvm/test/DebugInfo/X86/split-dwarf-multiple-cu-hash.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/split-dwarf-omit-empty.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/split-global.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sret.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sroasplit-1.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sroasplit-2.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sroasplit-3.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sroasplit-4.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sroasplit-5.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/sroasplit-dbg-declare.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/stack-args.ll"},
			{path: "../testdata/llvm/test/DebugInfo/X86/stack-value-dwarf2.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/stack-value-dwarf4.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/stack-value-piece.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/static_member_array.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/stmt-list.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/stmt-list-multiple-compile-units.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/string-offsets-multiple-cus.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/string-offsets-table.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/stringpool.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/strip-broken-debuginfo.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/struct-loc.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/subrange-type.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/subregisters.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/subreg.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/tail-merge.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/template.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/this-stack_value.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/tls.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/type_units_with_addresses.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/unattached-global.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/union-const.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/union-template.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/vector.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/vla-dependencies.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/vla-global.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/vla.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/vla-multi.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/void-typedef.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/xray-split-dwarf-interaction.ll"},
			//{path: "../testdata/llvm/test/DebugInfo/X86/zextload.ll"},

			// Coreutils.
			{path: "../testdata/coreutils/test/[.ll"},
			{path: "../testdata/coreutils/test/b2sum.ll"},
			{path: "../testdata/coreutils/test/base32.ll"},
			{path: "../testdata/coreutils/test/base64.ll"},
			{path: "../testdata/coreutils/test/basename.ll"},
			{path: "../testdata/coreutils/test/cat.ll"},
			{path: "../testdata/coreutils/test/chcon.ll"},
			{path: "../testdata/coreutils/test/chgrp.ll"},
			{path: "../testdata/coreutils/test/chmod.ll"},
			{path: "../testdata/coreutils/test/chown.ll"},
			{path: "../testdata/coreutils/test/chroot.ll"},
			{path: "../testdata/coreutils/test/cksum.ll"},
			{path: "../testdata/coreutils/test/comm.ll"},
			{path: "../testdata/coreutils/test/cp.ll"},
			{path: "../testdata/coreutils/test/csplit.ll"},
			{path: "../testdata/coreutils/test/cut.ll"},
			{path: "../testdata/coreutils/test/date.ll"},
			{path: "../testdata/coreutils/test/dd.ll"},
			{path: "../testdata/coreutils/test/df.ll"},
			{path: "../testdata/coreutils/test/dir.ll"},
			{path: "../testdata/coreutils/test/dircolors.ll"},
			{path: "../testdata/coreutils/test/dirname.ll"},
			{path: "../testdata/coreutils/test/du.ll"},
			{path: "../testdata/coreutils/test/echo.ll"},
			{path: "../testdata/coreutils/test/env.ll"},
			{path: "../testdata/coreutils/test/expand.ll"},
			{path: "../testdata/coreutils/test/expr.ll"},
			{path: "../testdata/coreutils/test/factor.ll"},
			{path: "../testdata/coreutils/test/false.ll"},
			{path: "../testdata/coreutils/test/fmt.ll"},
			{path: "../testdata/coreutils/test/fold.ll"},
			{path: "../testdata/coreutils/test/getlimits.ll"},
			{path: "../testdata/coreutils/test/ginstall.ll"},
			{path: "../testdata/coreutils/test/groups.ll"},
			{path: "../testdata/coreutils/test/head.ll"},
			{path: "../testdata/coreutils/test/hostid.ll"},
			{path: "../testdata/coreutils/test/id.ll"},
			{path: "../testdata/coreutils/test/join.ll"},
			{path: "../testdata/coreutils/test/kill.ll"},
			{path: "../testdata/coreutils/test/link.ll"},
			{path: "../testdata/coreutils/test/ln.ll"},
			{path: "../testdata/coreutils/test/logname.ll"},
			{path: "../testdata/coreutils/test/ls.ll"},
			{path: "../testdata/coreutils/test/make-prime-list.ll"},
			{path: "../testdata/coreutils/test/md5sum.ll"},
			{path: "../testdata/coreutils/test/mkdir.ll"},
			{path: "../testdata/coreutils/test/mkfifo.ll"},
			{path: "../testdata/coreutils/test/mknod.ll"},
			{path: "../testdata/coreutils/test/mktemp.ll"},
			{path: "../testdata/coreutils/test/mv.ll"},
			{path: "../testdata/coreutils/test/nice.ll"},
			{path: "../testdata/coreutils/test/nl.ll"},
			{path: "../testdata/coreutils/test/nohup.ll"},
			{path: "../testdata/coreutils/test/nproc.ll"},
			{path: "../testdata/coreutils/test/numfmt.ll"},
			{path: "../testdata/coreutils/test/od.ll"},
			{path: "../testdata/coreutils/test/paste.ll"},
			{path: "../testdata/coreutils/test/pathchk.ll"},
			{path: "../testdata/coreutils/test/pinky.ll"},
			{path: "../testdata/coreutils/test/pr.ll"},
			{path: "../testdata/coreutils/test/printenv.ll"},
			{path: "../testdata/coreutils/test/printf.ll"},
			{path: "../testdata/coreutils/test/ptx.ll"},
			{path: "../testdata/coreutils/test/pwd.ll"},
			{path: "../testdata/coreutils/test/readlink.ll"},
			{path: "../testdata/coreutils/test/realpath.ll"},
			{path: "../testdata/coreutils/test/rm.ll"},
			{path: "../testdata/coreutils/test/rmdir.ll"},
			{path: "../testdata/coreutils/test/runcon.ll"},
			{path: "../testdata/coreutils/test/seq.ll"},
			{path: "../testdata/coreutils/test/sha1sum.ll"},
			{path: "../testdata/coreutils/test/sha224sum.ll"},
			{path: "../testdata/coreutils/test/sha256sum.ll"},
			{path: "../testdata/coreutils/test/sha384sum.ll"},
			{path: "../testdata/coreutils/test/sha512sum.ll"},
			{path: "../testdata/coreutils/test/shred.ll"},
			{path: "../testdata/coreutils/test/shuf.ll"},
			{path: "../testdata/coreutils/test/sleep.ll"},
			{path: "../testdata/coreutils/test/sort.ll"},
			{path: "../testdata/coreutils/test/split.ll"},
			{path: "../testdata/coreutils/test/stat.ll"},
			{path: "../testdata/coreutils/test/stdbuf.ll"},
			{path: "../testdata/coreutils/test/stty.ll"},
			{path: "../testdata/coreutils/test/sum.ll"},
			{path: "../testdata/coreutils/test/sync.ll"},
			{path: "../testdata/coreutils/test/tac.ll"},
			{path: "../testdata/coreutils/test/tail.ll"},
			{path: "../testdata/coreutils/test/tee.ll"},
			{path: "../testdata/coreutils/test/test.ll"},
			{path: "../testdata/coreutils/test/timeout.ll"},
			{path: "../testdata/coreutils/test/touch.ll"},
			{path: "../testdata/coreutils/test/tr.ll"},
			{path: "../testdata/coreutils/test/true.ll"},
			{path: "../testdata/coreutils/test/truncate.ll"},
			{path: "../testdata/coreutils/test/tsort.ll"},
			{path: "../testdata/coreutils/test/tty.ll"},
			{path: "../testdata/coreutils/test/uname.ll"},
			{path: "../testdata/coreutils/test/unexpand.ll"},
			{path: "../testdata/coreutils/test/uniq.ll"},
			{path: "../testdata/coreutils/test/unlink.ll"},
			{path: "../testdata/coreutils/test/uptime.ll"},
			{path: "../testdata/coreutils/test/users.ll"},
			{path: "../testdata/coreutils/test/vdir.ll"},
			{path: "../testdata/coreutils/test/wc.ll"},
			{path: "../testdata/coreutils/test/who.ll"},
			{path: "../testdata/coreutils/test/whoami.ll"},
			{path: "../testdata/coreutils/test/yes.ll"},

			// SQLite.
			{path: "../testdata/sqlite/test/shell.ll"},
		*/
	}
	for _, g := range golden {
		if filepath.HasPrefix(g.path, "../testdata/") {
			if !osutil.Exists("../testdata/") {
				// Skip test cases from the llir/testdata submodule if not present.
				// Users may add this submodule using git clone --recursive.
				continue
			}
		}
		log.Printf("=== [ %s ] ===", g.path)
		m, err := ParseFile(g.path)
		if err != nil {
			t.Errorf("unable to parse %q into AST; %+v", g.path, err)
			continue
		}
		path := g.path
		if osutil.Exists(g.path + ".golden") {
			path = g.path + ".golden"
		}
		buf, err := ioutil.ReadFile(path)
		if err != nil {
			t.Errorf("unable to read %q; %+v", path, err)
			continue
		}
		want := string(buf)
		got := m.String()
		if want != got {
			if err := diffutil.Diff(want, got, words, filepath.Base(path)); err != nil {
				panic(err)
			}
			t.Errorf("module mismatch %q; expected `%s`, got `%s`", path, want, got)
			continue
		}
	}
}
