// generated by gen.go using 'go generate'; DO NOT EDIT.

// === [ Bitwise instructions ] ================================================
//
// References:
//    http://llvm.org/docs/LangRef.html#bitwise-binary-operations

package ast

// --- [ shl ] -----------------------------------------------------------------

// InstShl represents a shift left instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#shl-instruction
type InstShl struct {
	// Name of the local variable associated with the instruction.
	Name string
	// Operands.
	X, Y Value
}

// isValue ensures that only values can be assigned to the ast.Value interface.
func (*InstShl) isValue() {}

// isNamedValue ensures that only named values can be assigned to the
// ast.NamedValue interface.
func (*InstShl) isNamedValue() {}

// isInst ensures that only instructions can be assigned to the ast.Instruction
// interface.
func (*InstShl) isInst() {}

// --- [ lshr ] ----------------------------------------------------------------

// InstLShr represents a logical shift right instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#lshr-instruction
type InstLShr struct {
	// Name of the local variable associated with the instruction.
	Name string
	// Operands.
	X, Y Value
}

// isValue ensures that only values can be assigned to the ast.Value interface.
func (*InstLShr) isValue() {}

// isNamedValue ensures that only named values can be assigned to the
// ast.NamedValue interface.
func (*InstLShr) isNamedValue() {}

// isInst ensures that only instructions can be assigned to the ast.Instruction
// interface.
func (*InstLShr) isInst() {}

// --- [ ashr ] ----------------------------------------------------------------

// InstAShr represents an arithmetic shift right instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#ashr-instruction
type InstAShr struct {
	// Name of the local variable associated with the instruction.
	Name string
	// Operands.
	X, Y Value
}

// isValue ensures that only values can be assigned to the ast.Value interface.
func (*InstAShr) isValue() {}

// isNamedValue ensures that only named values can be assigned to the
// ast.NamedValue interface.
func (*InstAShr) isNamedValue() {}

// isInst ensures that only instructions can be assigned to the ast.Instruction
// interface.
func (*InstAShr) isInst() {}

// --- [ and ] -----------------------------------------------------------------

// InstAnd represents an AND instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#and-instruction
type InstAnd struct {
	// Name of the local variable associated with the instruction.
	Name string
	// Operands.
	X, Y Value
}

// isValue ensures that only values can be assigned to the ast.Value interface.
func (*InstAnd) isValue() {}

// isNamedValue ensures that only named values can be assigned to the
// ast.NamedValue interface.
func (*InstAnd) isNamedValue() {}

// isInst ensures that only instructions can be assigned to the ast.Instruction
// interface.
func (*InstAnd) isInst() {}

// --- [ or ] ------------------------------------------------------------------

// InstOr represents an OR instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#or-instruction
type InstOr struct {
	// Name of the local variable associated with the instruction.
	Name string
	// Operands.
	X, Y Value
}

// isValue ensures that only values can be assigned to the ast.Value interface.
func (*InstOr) isValue() {}

// isNamedValue ensures that only named values can be assigned to the
// ast.NamedValue interface.
func (*InstOr) isNamedValue() {}

// isInst ensures that only instructions can be assigned to the ast.Instruction
// interface.
func (*InstOr) isInst() {}

// --- [ xor ] -----------------------------------------------------------------

// InstXor represents an exclusive-OR instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#xor-instruction
type InstXor struct {
	// Name of the local variable associated with the instruction.
	Name string
	// Operands.
	X, Y Value
}

// isValue ensures that only values can be assigned to the ast.Value interface.
func (*InstXor) isValue() {}

// isNamedValue ensures that only named values can be assigned to the
// ast.NamedValue interface.
func (*InstXor) isNamedValue() {}

// isInst ensures that only instructions can be assigned to the ast.Instruction
// interface.
func (*InstXor) isInst() {}
