// Code generated by "stringer -linecomment -type AllocKind"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AllocKindAlloc-1]
	_ = x[AllocKindRealloc-2]
	_ = x[AllocKindFree-4]
	_ = x[AllocKindUninitialized-8]
	_ = x[AllocKindZeroed-16]
	_ = x[AllocKindAligned-32]
}

const (
	_AllocKind_name_0 = "allocrealloc"
	_AllocKind_name_1 = "free"
	_AllocKind_name_2 = "uninitialized"
	_AllocKind_name_3 = "zeroed"
	_AllocKind_name_4 = "aligned"
)

var (
	_AllocKind_index_0 = [...]uint8{0, 5, 12}
)

func (i AllocKind) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _AllocKind_name_0[_AllocKind_index_0[i]:_AllocKind_index_0[i+1]]
	case i == 4:
		return _AllocKind_name_1
	case i == 8:
		return _AllocKind_name_2
	case i == 16:
		return _AllocKind_name_3
	case i == 32:
		return _AllocKind_name_4
	default:
		return "AllocKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
