// Code generated by "stringer -linecomment -type AtomicOp"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AtomicOpAdd-1]
	_ = x[AtomicOpAnd-2]
	_ = x[AtomicOpFAdd-3]
	_ = x[AtomicOpFSub-4]
	_ = x[AtomicOpMax-5]
	_ = x[AtomicOpMin-6]
	_ = x[AtomicOpNAnd-7]
	_ = x[AtomicOpOr-8]
	_ = x[AtomicOpSub-9]
	_ = x[AtomicOpUMax-10]
	_ = x[AtomicOpUMin-11]
	_ = x[AtomicOpXChg-12]
	_ = x[AtomicOpXor-13]
}

const _AtomicOp_name = "addandfaddfsubmaxminnandorsubumaxuminxchgxor"

var _AtomicOp_index = [...]uint8{0, 3, 6, 10, 14, 17, 20, 24, 26, 29, 33, 37, 41, 44}

func (i AtomicOp) String() string {
	i -= 1
	if i >= AtomicOp(len(_AtomicOp_index)-1) {
		return "AtomicOp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AtomicOp_name[_AtomicOp_index[i]:_AtomicOp_index[i+1]]
}
