// Code generated by "stringer -linecomment -type AtomicOp"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AtomicOpAdd-1]
	_ = x[AtomicOpAnd-2]
	_ = x[AtomicOpFAdd-3]
	_ = x[AtomicOpFMax-4]
	_ = x[AtomicOpFMin-5]
	_ = x[AtomicOpFSub-6]
	_ = x[AtomicOpMax-7]
	_ = x[AtomicOpMin-8]
	_ = x[AtomicOpNAnd-9]
	_ = x[AtomicOpOr-10]
	_ = x[AtomicOpSub-11]
	_ = x[AtomicOpUMax-12]
	_ = x[AtomicOpUMin-13]
	_ = x[AtomicOpXChg-14]
	_ = x[AtomicOpXor-15]
}

const _AtomicOp_name = "addandfaddfmaxfminfsubmaxminnandorsubumaxuminxchgxor"

var _AtomicOp_index = [...]uint8{0, 3, 6, 10, 14, 18, 22, 25, 28, 32, 34, 37, 41, 45, 49, 52}

func (i AtomicOp) String() string {
	i -= 1
	if i >= AtomicOp(len(_AtomicOp_index)-1) {
		return "AtomicOp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AtomicOp_name[_AtomicOp_index[i]:_AtomicOp_index[i+1]]
}
