// Code generated by "stringer -linecomment -type AtomicOp"; DO NOT EDIT.

package enum

import "strconv"

const _AtomicOp_name = "addandmaxminnandorsubumaxuminxchgxor"

var _AtomicOp_index = [...]uint8{0, 3, 6, 9, 12, 16, 18, 21, 25, 29, 33, 36}

func (i AtomicOp) String() string {
	i -= 1
	if i >= AtomicOp(len(_AtomicOp_index)-1) {
		return "AtomicOp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AtomicOp_name[_AtomicOp_index[i]:_AtomicOp_index[i+1]]
}
