// Code generated by "stringer -linecomment -type ChecksumKind"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChecksumKindMD5-1]
	_ = x[ChecksumKindSHA1-2]
}

const _ChecksumKind_name = "CSK_MD5CSK_SHA1"

var _ChecksumKind_index = [...]uint8{0, 7, 15}

func (i ChecksumKind) String() string {
	i -= 1
	if i >= ChecksumKind(len(_ChecksumKind_index)-1) {
		return "ChecksumKind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ChecksumKind_name[_ChecksumKind_index[i]:_ChecksumKind_index[i+1]]
}
