// Code generated by "stringer -linecomment -type ClauseType"; DO NOT EDIT.

package enum

import "strconv"

const _ClauseType_name = "catchfilter"

var _ClauseType_index = [...]uint8{0, 5, 11}

func (i ClauseType) String() string {
	i -= 1
	if i >= ClauseType(len(_ClauseType_index)-1) {
		return "ClauseType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ClauseType_name[_ClauseType_index[i]:_ClauseType_index[i+1]]
}
