// Code generated by "stringer -type DIFlag"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DIFlagZero-0]
	_ = x[DIFlagPrivate-1]
	_ = x[DIFlagProtected-2]
	_ = x[DIFlagPublic-3]
	_ = x[DIFlagFwdDecl-4]
	_ = x[DIFlagAppleBlock-8]
	_ = x[DIFlagBlockByrefStruct-16]
	_ = x[DIFlagVirtual-32]
	_ = x[DIFlagArtificial-64]
	_ = x[DIFlagExplicit-128]
	_ = x[DIFlagPrototyped-256]
	_ = x[DIFlagObjcClassComplete-512]
	_ = x[DIFlagObjectPointer-1024]
	_ = x[DIFlagVector-2048]
	_ = x[DIFlagStaticMember-4096]
	_ = x[DIFlagLValueReference-8192]
	_ = x[DIFlagRValueReference-16384]
	_ = x[DIFlagReserved-32768]
	_ = x[DIFlagSingleInheritance-65536]
	_ = x[DIFlagMultipleInheritance-131072]
	_ = x[DIFlagVirtualInheritance-196608]
	_ = x[DIFlagIntroducedVirtual-262144]
	_ = x[DIFlagBitField-524288]
	_ = x[DIFlagNoReturn-1048576]
	_ = x[DIFlagTypePassByValue-4194304]
	_ = x[DIFlagTypePassByReference-8388608]
	_ = x[DIFlagEnumClass-16777216]
	_ = x[DIFlagThunk-33554432]
	_ = x[DIFlagNonTrivial-67108864]
	_ = x[DIFlagBigEndian-134217728]
	_ = x[DIFlagLittleEndian-268435456]
}

const _DIFlag_name = "DIFlagZeroDIFlagPrivateDIFlagProtectedDIFlagPublicDIFlagFwdDeclDIFlagAppleBlockDIFlagBlockByrefStructDIFlagVirtualDIFlagArtificialDIFlagExplicitDIFlagPrototypedDIFlagObjcClassCompleteDIFlagObjectPointerDIFlagVectorDIFlagStaticMemberDIFlagLValueReferenceDIFlagRValueReferenceDIFlagReservedDIFlagSingleInheritanceDIFlagMultipleInheritanceDIFlagVirtualInheritanceDIFlagIntroducedVirtualDIFlagBitFieldDIFlagNoReturnDIFlagTypePassByValueDIFlagTypePassByReferenceDIFlagEnumClassDIFlagThunkDIFlagNonTrivialDIFlagBigEndianDIFlagLittleEndian"

var _DIFlag_map = map[DIFlag]string{
	0:         _DIFlag_name[0:10],
	1:         _DIFlag_name[10:23],
	2:         _DIFlag_name[23:38],
	3:         _DIFlag_name[38:50],
	4:         _DIFlag_name[50:63],
	8:         _DIFlag_name[63:79],
	16:        _DIFlag_name[79:101],
	32:        _DIFlag_name[101:114],
	64:        _DIFlag_name[114:130],
	128:       _DIFlag_name[130:144],
	256:       _DIFlag_name[144:160],
	512:       _DIFlag_name[160:183],
	1024:      _DIFlag_name[183:202],
	2048:      _DIFlag_name[202:214],
	4096:      _DIFlag_name[214:232],
	8192:      _DIFlag_name[232:253],
	16384:     _DIFlag_name[253:274],
	32768:     _DIFlag_name[274:288],
	65536:     _DIFlag_name[288:311],
	131072:    _DIFlag_name[311:336],
	196608:    _DIFlag_name[336:360],
	262144:    _DIFlag_name[360:383],
	524288:    _DIFlag_name[383:397],
	1048576:   _DIFlag_name[397:411],
	4194304:   _DIFlag_name[411:432],
	8388608:   _DIFlag_name[432:457],
	16777216:  _DIFlag_name[457:472],
	33554432:  _DIFlag_name[472:483],
	67108864:  _DIFlag_name[483:499],
	134217728: _DIFlag_name[499:514],
	268435456: _DIFlag_name[514:532],
}

func (i DIFlag) String() string {
	if str, ok := _DIFlag_map[i]; ok {
		return str
	}
	return "DIFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
