// Code generated by "stringer -linecomment -type DwarfAttEncoding"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DwarfAttEncodingAddress-1]
	_ = x[DwarfAttEncodingBoolean-2]
	_ = x[DwarfAttEncodingComplexFloat-3]
	_ = x[DwarfAttEncodingFloat-4]
	_ = x[DwarfAttEncodingSigned-5]
	_ = x[DwarfAttEncodingSignedChar-6]
	_ = x[DwarfAttEncodingUnsigned-7]
	_ = x[DwarfAttEncodingUnsignedChar-8]
	_ = x[DwarfAttEncodingImaginaryFloat-9]
	_ = x[DwarfAttEncodingPackedDecimal-10]
	_ = x[DwarfAttEncodingNumericString-11]
	_ = x[DwarfAttEncodingEdited-12]
	_ = x[DwarfAttEncodingSignedFixed-13]
	_ = x[DwarfAttEncodingUnsignedFixed-14]
	_ = x[DwarfAttEncodingDecimalFloat-15]
	_ = x[DwarfAttEncodingUTF-16]
	_ = x[DwarfAttEncodingUCS-17]
	_ = x[DwarfAttEncodingASCII-18]
}

const _DwarfAttEncoding_name = "DW_ATE_addressDW_ATE_booleanDW_ATE_complex_floatDW_ATE_floatDW_ATE_signedDW_ATE_signed_charDW_ATE_unsignedDW_ATE_unsigned_charDW_ATE_imaginary_floatDW_ATE_packed_decimalDW_ATE_numeric_stringDW_ATE_editedDW_ATE_signed_fixedDW_ATE_unsigned_fixedDW_ATE_decimal_floatDW_ATE_UTFDW_ATE_UCSDW_ATE_ASCII"

var _DwarfAttEncoding_index = [...]uint16{0, 14, 28, 48, 60, 73, 91, 106, 126, 148, 169, 190, 203, 222, 243, 263, 273, 283, 295}

func (i DwarfAttEncoding) String() string {
	i -= 1
	if i < 0 || i >= DwarfAttEncoding(len(_DwarfAttEncoding_index)-1) {
		return "DwarfAttEncoding(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DwarfAttEncoding_name[_DwarfAttEncoding_index[i]:_DwarfAttEncoding_index[i+1]]
}
