// Code generated by "stringer -linecomment -type DwarfMacinfo"; DO NOT EDIT.

package enum

import "strconv"

const (
	_DwarfMacinfo_name_0 = "DW_MACINFO_defineDW_MACINFO_undefDW_MACINFO_start_fileDW_MACINFO_end_file"
	_DwarfMacinfo_name_1 = "DW_MACINFO_vendor_ext"
)

var (
	_DwarfMacinfo_index_0 = [...]uint8{0, 17, 33, 54, 73}
)

func (i DwarfMacinfo) String() string {
	switch {
	case 1 <= i && i <= 4:
		i -= 1
		return _DwarfMacinfo_name_0[_DwarfMacinfo_index_0[i]:_DwarfMacinfo_index_0[i+1]]
	case i == 255:
		return _DwarfMacinfo_name_1
	default:
		return "DwarfMacinfo(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
