// Code generated by "stringer -linecomment -type EmissionKind"; DO NOT EDIT.

package enum

import "strconv"

const _EmissionKind_name = "NoDebugFullDebugLineTablesOnly"

var _EmissionKind_index = [...]uint8{0, 7, 16, 30}

func (i EmissionKind) String() string {
	if i < 0 || i >= EmissionKind(len(_EmissionKind_index)-1) {
		return "EmissionKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EmissionKind_name[_EmissionKind_index[i]:_EmissionKind_index[i+1]]
}
