// Code generated by "stringer -linecomment -type FastMathFlag"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FastMathFlagAFn-0]
	_ = x[FastMathFlagARcp-1]
	_ = x[FastMathFlagContract-2]
	_ = x[FastMathFlagFast-3]
	_ = x[FastMathFlagNInf-4]
	_ = x[FastMathFlagNNaN-5]
	_ = x[FastMathFlagNSZ-6]
	_ = x[FastMathFlagReassoc-7]
}

const _FastMathFlag_name = "afnarcpcontractfastninfnnannszreassoc"

var _FastMathFlag_index = [...]uint8{0, 3, 7, 15, 19, 23, 27, 30, 37}

func (i FastMathFlag) String() string {
	if i >= FastMathFlag(len(_FastMathFlag_index)-1) {
		return "FastMathFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FastMathFlag_name[_FastMathFlag_index[i]:_FastMathFlag_index[i+1]]
}
