// Code generated by "stringer -linecomment -type FuncAttr"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FuncAttrAlwaysInline-0]
	_ = x[FuncAttrArgMemOnly-1]
	_ = x[FuncAttrBuiltin-2]
	_ = x[FuncAttrCold-3]
	_ = x[FuncAttrConvergent-4]
	_ = x[FuncAttrInaccessibleMemOnly-5]
	_ = x[FuncAttrInaccessibleMemOrArgMemOnly-6]
	_ = x[FuncAttrInlineHint-7]
	_ = x[FuncAttrJumpTable-8]
	_ = x[FuncAttrMinSize-9]
	_ = x[FuncAttrNaked-10]
	_ = x[FuncAttrNoBuiltin-11]
	_ = x[FuncAttrNoCFCheck-12]
	_ = x[FuncAttrNoDuplicate-13]
	_ = x[FuncAttrNoFree-14]
	_ = x[FuncAttrNoImplicitFloat-15]
	_ = x[FuncAttrNoInline-16]
	_ = x[FuncAttrNoMerge-17]
	_ = x[FuncAttrNonLazyBind-18]
	_ = x[FuncAttrNoRecurse-19]
	_ = x[FuncAttrNoRedZone-20]
	_ = x[FuncAttrNoReturn-21]
	_ = x[FuncAttrNoSync-22]
	_ = x[FuncAttrNoUndef-23]
	_ = x[FuncAttrNoUnwind-24]
	_ = x[FuncAttrNullPointerIsValid-25]
	_ = x[FuncAttrOptForFuzzing-26]
	_ = x[FuncAttrOptNone-27]
	_ = x[FuncAttrOptSize-28]
	_ = x[FuncAttrReadNone-29]
	_ = x[FuncAttrReadOnly-30]
	_ = x[FuncAttrReturnsTwice-31]
	_ = x[FuncAttrSafeStack-32]
	_ = x[FuncAttrSanitizeAddress-33]
	_ = x[FuncAttrSanitizeHWAddress-34]
	_ = x[FuncAttrSanitizeMemory-35]
	_ = x[FuncAttrSanitizeMemTag-36]
	_ = x[FuncAttrSanitizeThread-37]
	_ = x[FuncAttrShadowCallStack-38]
	_ = x[FuncAttrSpeculatable-39]
	_ = x[FuncAttrSpeculativeLoadHardening-40]
	_ = x[FuncAttrSSP-41]
	_ = x[FuncAttrSSPReq-42]
	_ = x[FuncAttrSSPStrong-43]
	_ = x[FuncAttrStrictFP-44]
	_ = x[FuncAttrUwtable-45]
	_ = x[FuncAttrWillReturn-46]
	_ = x[FuncAttrWriteOnly-47]
}

const _FuncAttr_name = "alwaysinlineargmemonlybuiltincoldconvergentinaccessiblememonlyinaccessiblemem_or_argmemonlyinlinehintjumptableminsizenakednobuiltinnocf_checknoduplicatenofreenoimplicitfloatnoinlinenomergenonlazybindnorecursenoredzonenoreturnnosyncnoundefnounwindnull_pointer_is_validoptforfuzzingoptnoneoptsizereadnonereadonlyreturns_twicesafestacksanitize_addresssanitize_hwaddresssanitize_memorysanitize_memtagsanitize_threadshadowcallstackspeculatablespeculative_load_hardeningsspsspreqsspstrongstrictfpuwtablewillreturnwriteonly"

var _FuncAttr_index = [...]uint16{0, 12, 22, 29, 33, 43, 62, 91, 101, 110, 117, 122, 131, 141, 152, 158, 173, 181, 188, 199, 208, 217, 225, 231, 238, 246, 267, 280, 287, 294, 302, 310, 323, 332, 348, 366, 381, 396, 411, 426, 438, 464, 467, 473, 482, 490, 497, 507, 516}

func (i FuncAttr) String() string {
	if i >= FuncAttr(len(_FuncAttr_index)-1) {
		return "FuncAttr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FuncAttr_name[_FuncAttr_index[i]:_FuncAttr_index[i+1]]
}
