// Code generated by "stringer -linecomment -type FuncAttr"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FuncAttrAlwaysInline-0]
	_ = x[FuncAttrArgMemOnly-1]
	_ = x[FuncAttrBuiltin-2]
	_ = x[FuncAttrCold-3]
	_ = x[FuncAttrConvergent-4]
	_ = x[FuncAttrDisableSanitizerInstrumentation-5]
	_ = x[FuncAttrHot-6]
	_ = x[FuncAttrInaccessibleMemOnly-7]
	_ = x[FuncAttrInaccessibleMemOrArgMemOnly-8]
	_ = x[FuncAttrInlineHint-9]
	_ = x[FuncAttrJumpTable-10]
	_ = x[FuncAttrMinSize-11]
	_ = x[FuncAttrMustProgress-12]
	_ = x[FuncAttrNaked-13]
	_ = x[FuncAttrNoBuiltin-14]
	_ = x[FuncAttrNoCFCheck-15]
	_ = x[FuncAttrNoCallback-16]
	_ = x[FuncAttrNoDuplicate-17]
	_ = x[FuncAttrNoFree-18]
	_ = x[FuncAttrNoImplicitFloat-19]
	_ = x[FuncAttrNoInline-20]
	_ = x[FuncAttrNoMerge-21]
	_ = x[FuncAttrNoProfile-22]
	_ = x[FuncAttrNoRecurse-23]
	_ = x[FuncAttrNoRedZone-24]
	_ = x[FuncAttrNoReturn-25]
	_ = x[FuncAttrNoSanitizeCoverage-26]
	_ = x[FuncAttrNoSync-27]
	_ = x[FuncAttrNoUnwind-28]
	_ = x[FuncAttrNonLazyBind-29]
	_ = x[FuncAttrNullPointerIsValid-30]
	_ = x[FuncAttrOptForFuzzing-31]
	_ = x[FuncAttrOptNone-32]
	_ = x[FuncAttrOptSize-33]
	_ = x[FuncAttrReadNone-34]
	_ = x[FuncAttrReadOnly-35]
	_ = x[FuncAttrReturnsTwice-36]
	_ = x[FuncAttrSSP-37]
	_ = x[FuncAttrSSPReq-38]
	_ = x[FuncAttrSSPStrong-39]
	_ = x[FuncAttrSafeStack-40]
	_ = x[FuncAttrSanitizeAddress-41]
	_ = x[FuncAttrSanitizeHWAddress-42]
	_ = x[FuncAttrSanitizeMemTag-43]
	_ = x[FuncAttrSanitizeMemory-44]
	_ = x[FuncAttrSanitizeThread-45]
	_ = x[FuncAttrShadowCallStack-46]
	_ = x[FuncAttrSpeculatable-47]
	_ = x[FuncAttrSpeculativeLoadHardening-48]
	_ = x[FuncAttrStrictFP-49]
	_ = x[FuncAttrUwtable-50]
	_ = x[FuncAttrWillReturn-51]
	_ = x[FuncAttrWriteOnly-52]
}

const _FuncAttr_name = "alwaysinlineargmemonlybuiltincoldconvergentdisable_sanitizer_instrumentationhotinaccessiblememonlyinaccessiblemem_or_argmemonlyinlinehintjumptableminsizemustprogressnakednobuiltinnocf_checknocallbacknoduplicatenofreenoimplicitfloatnoinlinenomergenoprofilenorecursenoredzonenoreturnnosanitize_coveragenosyncnounwindnonlazybindnull_pointer_is_validoptforfuzzingoptnoneoptsizereadnonereadonlyreturns_twicesspsspreqsspstrongsafestacksanitize_addresssanitize_hwaddresssanitize_memtagsanitize_memorysanitize_threadshadowcallstackspeculatablespeculative_load_hardeningstrictfpuwtablewillreturnwriteonly"

var _FuncAttr_index = [...]uint16{0, 12, 22, 29, 33, 43, 76, 79, 98, 127, 137, 146, 153, 165, 170, 179, 189, 199, 210, 216, 231, 239, 246, 255, 264, 273, 281, 300, 306, 314, 325, 346, 359, 366, 373, 381, 389, 402, 405, 411, 420, 429, 445, 463, 478, 493, 508, 523, 535, 561, 569, 576, 586, 595}

func (i FuncAttr) String() string {
	if i >= FuncAttr(len(_FuncAttr_index)-1) {
		return "FuncAttr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FuncAttr_name[_FuncAttr_index[i]:_FuncAttr_index[i+1]]
}
