// Code generated by "stringer -linecomment -type FuncAttr"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FuncAttrAlwaysInline-0]
	_ = x[FuncAttrArgMemOnly-1]
	_ = x[FuncAttrBuiltin-2]
	_ = x[FuncAttrCold-3]
	_ = x[FuncAttrConvergent-4]
	_ = x[FuncAttrDisableSanitizerInstrumentation-5]
	_ = x[FuncAttrFnRetThunkExtern-6]
	_ = x[FuncAttrHot-7]
	_ = x[FuncAttrInaccessibleMemOnly-8]
	_ = x[FuncAttrInaccessibleMemOrArgMemOnly-9]
	_ = x[FuncAttrInlineHint-10]
	_ = x[FuncAttrJumpTable-11]
	_ = x[FuncAttrMinSize-12]
	_ = x[FuncAttrMustProgress-13]
	_ = x[FuncAttrNaked-14]
	_ = x[FuncAttrNoBuiltin-15]
	_ = x[FuncAttrNoCFCheck-16]
	_ = x[FuncAttrNoCallback-17]
	_ = x[FuncAttrNoDuplicate-18]
	_ = x[FuncAttrNoFree-19]
	_ = x[FuncAttrNoImplicitFloat-20]
	_ = x[FuncAttrNoInline-21]
	_ = x[FuncAttrNoMerge-22]
	_ = x[FuncAttrNoProfile-23]
	_ = x[FuncAttrNoRecurse-24]
	_ = x[FuncAttrNoRedZone-25]
	_ = x[FuncAttrNoReturn-26]
	_ = x[FuncAttrNoSanitizeBounds-27]
	_ = x[FuncAttrNoSanitizeCoverage-28]
	_ = x[FuncAttrNoSync-29]
	_ = x[FuncAttrNoUnwind-30]
	_ = x[FuncAttrNonLazyBind-31]
	_ = x[FuncAttrNullPointerIsValid-32]
	_ = x[FuncAttrOptForFuzzing-33]
	_ = x[FuncAttrOptNone-34]
	_ = x[FuncAttrOptSize-35]
	_ = x[FuncAttrPreSplitCoroutine-36]
	_ = x[FuncAttrReadNone-37]
	_ = x[FuncAttrReadOnly-38]
	_ = x[FuncAttrReturnsTwice-39]
	_ = x[FuncAttrSSP-40]
	_ = x[FuncAttrSSPReq-41]
	_ = x[FuncAttrSSPStrong-42]
	_ = x[FuncAttrSafeStack-43]
	_ = x[FuncAttrSanitizeAddress-44]
	_ = x[FuncAttrSanitizeHWAddress-45]
	_ = x[FuncAttrSanitizeMemTag-46]
	_ = x[FuncAttrSanitizeMemory-47]
	_ = x[FuncAttrSanitizeThread-48]
	_ = x[FuncAttrShadowCallStack-49]
	_ = x[FuncAttrSpeculatable-50]
	_ = x[FuncAttrSpeculativeLoadHardening-51]
	_ = x[FuncAttrStrictFP-52]
	_ = x[FuncAttrUwtable-53]
	_ = x[FuncAttrWillReturn-54]
	_ = x[FuncAttrWriteOnly-55]
}

const _FuncAttr_name = "alwaysinlineargmemonlybuiltincoldconvergentdisable_sanitizer_instrumentationfn_ret_thunk_externhotinaccessiblememonlyinaccessiblemem_or_argmemonlyinlinehintjumptableminsizemustprogressnakednobuiltinnocf_checknocallbacknoduplicatenofreenoimplicitfloatnoinlinenomergenoprofilenorecursenoredzonenoreturnnosanitize_boundsnosanitize_coveragenosyncnounwindnonlazybindnull_pointer_is_validoptforfuzzingoptnoneoptsizepresplitcoroutinereadnonereadonlyreturns_twicesspsspreqsspstrongsafestacksanitize_addresssanitize_hwaddresssanitize_memtagsanitize_memorysanitize_threadshadowcallstackspeculatablespeculative_load_hardeningstrictfpuwtablewillreturnwriteonly"

var _FuncAttr_index = [...]uint16{0, 12, 22, 29, 33, 43, 76, 95, 98, 117, 146, 156, 165, 172, 184, 189, 198, 208, 218, 229, 235, 250, 258, 265, 274, 283, 292, 300, 317, 336, 342, 350, 361, 382, 395, 402, 409, 426, 434, 442, 455, 458, 464, 473, 482, 498, 516, 531, 546, 561, 576, 588, 614, 622, 629, 639, 648}

func (i FuncAttr) String() string {
	if i >= FuncAttr(len(_FuncAttr_index)-1) {
		return "FuncAttr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FuncAttr_name[_FuncAttr_index[i]:_FuncAttr_index[i+1]]
}
