// Code generated by "stringer -linecomment -type Linkage"; DO NOT EDIT.

package enum

import "strconv"

const _Linkage_name = "noneappendingavailable_externallycommoninternallinkoncelinkonce_odrprivateweakweak_odrexternalextern_weak"

var _Linkage_index = [...]uint8{0, 4, 13, 33, 39, 47, 55, 67, 74, 78, 86, 94, 105}

func (i Linkage) String() string {
	if i >= Linkage(len(_Linkage_index)-1) {
		return "Linkage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Linkage_name[_Linkage_index[i]:_Linkage_index[i+1]]
}
