// Code generated by "stringer -linecomment -type NameTableKind"; DO NOT EDIT.

package enum

import "strconv"

const _NameTableKind_name = "NoneDefaultGNU"

var _NameTableKind_index = [...]uint8{0, 4, 11, 14}

func (i NameTableKind) String() string {
	if i >= NameTableKind(len(_NameTableKind_index)-1) {
		return "NameTableKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NameTableKind_name[_NameTableKind_index[i]:_NameTableKind_index[i+1]]
}
