// Code generated by "stringer -linecomment -type OverflowFlag"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OverflowFlagNSW-0]
	_ = x[OverflowFlagNUW-1]
}

const _OverflowFlag_name = "nswnuw"

var _OverflowFlag_index = [...]uint8{0, 3, 6}

func (i OverflowFlag) String() string {
	if i >= OverflowFlag(len(_OverflowFlag_index)-1) {
		return "OverflowFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OverflowFlag_name[_OverflowFlag_index[i]:_OverflowFlag_index[i+1]]
}
