// Code generated by "stringer -linecomment -type ParamAttr"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParamAttrImmArg-0]
	_ = x[ParamAttrInAlloca-1]
	_ = x[ParamAttrInReg-2]
	_ = x[ParamAttrNest-3]
	_ = x[ParamAttrNoAlias-4]
	_ = x[ParamAttrNoCapture-5]
	_ = x[ParamAttrNoFree-6]
	_ = x[ParamAttrNonNull-7]
	_ = x[ParamAttrNoMerge-8]
	_ = x[ParamAttrNullPointerIsValid-9]
	_ = x[ParamAttrReadNone-10]
	_ = x[ParamAttrReadOnly-11]
	_ = x[ParamAttrReturned-12]
	_ = x[ParamAttrSignExt-13]
	_ = x[ParamAttrSRet-14]
	_ = x[ParamAttrSwiftError-15]
	_ = x[ParamAttrSwiftSelf-16]
	_ = x[ParamAttrWriteOnly-17]
	_ = x[ParamAttrZeroExt-18]
}

const _ParamAttr_name = "immarginallocainregnestnoaliasnocapturenofreenonnullnomergenull_pointer_is_validreadnonereadonlyreturnedsignextsretswifterrorswiftselfwriteonlyzeroext"

var _ParamAttr_index = [...]uint8{0, 6, 14, 19, 23, 30, 39, 45, 52, 59, 80, 88, 96, 104, 111, 115, 125, 134, 143, 150}

func (i ParamAttr) String() string {
	if i >= ParamAttr(len(_ParamAttr_index)-1) {
		return "ParamAttr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParamAttr_name[_ParamAttr_index[i]:_ParamAttr_index[i+1]]
}
