// Code generated by "stringer -linecomment -type ParamAttr"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParamAttrImmArg-0]
	_ = x[ParamAttrInAlloca-1]
	_ = x[ParamAttrInReg-2]
	_ = x[ParamAttrNest-3]
	_ = x[ParamAttrNoAlias-4]
	_ = x[ParamAttrNoCapture-5]
	_ = x[ParamAttrNoFree-6]
	_ = x[ParamAttrNonNull-7]
	_ = x[ParamAttrReadNone-8]
	_ = x[ParamAttrReadOnly-9]
	_ = x[ParamAttrReturned-10]
	_ = x[ParamAttrSignExt-11]
	_ = x[ParamAttrSRet-12]
	_ = x[ParamAttrSwiftError-13]
	_ = x[ParamAttrSwiftSelf-14]
	_ = x[ParamAttrWriteOnly-15]
	_ = x[ParamAttrZeroExt-16]
}

const _ParamAttr_name = "immarginallocainregnestnoaliasnocapturenofreenonnullreadnonereadonlyreturnedsignextsretswifterrorswiftselfwriteonlyzeroext"

var _ParamAttr_index = [...]uint8{0, 6, 14, 19, 23, 30, 39, 45, 52, 60, 68, 76, 83, 87, 97, 106, 115, 122}

func (i ParamAttr) String() string {
	if i >= ParamAttr(len(_ParamAttr_index)-1) {
		return "ParamAttr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParamAttr_name[_ParamAttr_index[i]:_ParamAttr_index[i+1]]
}
