// Code generated by "stringer -linecomment -type Preemption"; DO NOT EDIT.

package enum

import "strconv"

const _Preemption_name = "nonedso_localdso_preemptable"

var _Preemption_index = [...]uint8{0, 4, 13, 28}

func (i Preemption) String() string {
	if i >= Preemption(len(_Preemption_index)-1) {
		return "Preemption(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Preemption_name[_Preemption_index[i]:_Preemption_index[i+1]]
}
