// Code generated by "stringer -linecomment -type Tail"; DO NOT EDIT.

package enum

import "strconv"

const _Tail_name = "nonemusttailnotailtail"

var _Tail_index = [...]uint8{0, 4, 12, 18, 22}

func (i Tail) String() string {
	if i >= Tail(len(_Tail_index)-1) {
		return "Tail(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tail_name[_Tail_index[i]:_Tail_index[i+1]]
}
