// generated by gen.go using 'go generate'; DO NOT EDIT.

// === [ Bitwise instructions ] ================================================
//
// References:
//    http://llvm.org/docs/LangRef.html#bitwise-binary-operations

package ir

import (
	"fmt"

	"github.com/llir/llvm/ir/internal/enc"
	"github.com/llir/llvm/ir/types"
	"github.com/llir/llvm/ir/value"
)

// --- [ shl ] -----------------------------------------------------------------

// InstShL represents a shift left instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#shl-instruction
type InstShL struct {
	// Parent basic block.
	parent *BasicBlock
	// Identifier associated with the instruction.
	ident string
	// Operands.
	x, y value.Value
}

// NewShL returns a new shl instruction based on the given operands.
func NewShL(x, y value.Value) *InstShL {
	return &InstShL{x: x, y: y}
}

// Type returns the type of the instruction.
func (inst *InstShL) Type() types.Type {
	return inst.x.Type()
}

// Ident returns the identifier associated with the instruction.
func (inst *InstShL) Ident() string {
	return enc.Local(inst.ident)
}

// SetIdent sets the identifier associated with the instruction.
func (inst *InstShL) SetIdent(ident string) {
	inst.ident = ident
}

// LLVMString returns the LLVM syntax representation of the instruction.
func (inst *InstShL) LLVMString() string {
	return fmt.Sprintf("%s = shl %s %s, %s",
		inst.Ident(),
		inst.Type().LLVMString(),
		inst.x.Ident(),
		inst.y.Ident())
}

// Parent returns the parent basic block of the instruction.
func (inst *InstShL) Parent() *BasicBlock {
	return inst.parent
}

// SetParent sets the parent basic block of the instruction.
func (inst *InstShL) SetParent(parent *BasicBlock) {
	inst.parent = parent
}

// X returns the x operand of the shl instruction.
func (inst *InstShL) X() value.Value {
	return inst.x
}

// Y returns the y operand of the shl instruction.
func (inst *InstShL) Y() value.Value {
	return inst.y
}

// --- [ lshr ] ----------------------------------------------------------------

// InstLShR represents a logical shift right instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#lshr-instruction
type InstLShR struct {
	// Parent basic block.
	parent *BasicBlock
	// Identifier associated with the instruction.
	ident string
	// Operands.
	x, y value.Value
}

// NewLShR returns a new lshr instruction based on the given operands.
func NewLShR(x, y value.Value) *InstLShR {
	return &InstLShR{x: x, y: y}
}

// Type returns the type of the instruction.
func (inst *InstLShR) Type() types.Type {
	return inst.x.Type()
}

// Ident returns the identifier associated with the instruction.
func (inst *InstLShR) Ident() string {
	return enc.Local(inst.ident)
}

// SetIdent sets the identifier associated with the instruction.
func (inst *InstLShR) SetIdent(ident string) {
	inst.ident = ident
}

// LLVMString returns the LLVM syntax representation of the instruction.
func (inst *InstLShR) LLVMString() string {
	return fmt.Sprintf("%s = lshr %s %s, %s",
		inst.Ident(),
		inst.Type().LLVMString(),
		inst.x.Ident(),
		inst.y.Ident())
}

// Parent returns the parent basic block of the instruction.
func (inst *InstLShR) Parent() *BasicBlock {
	return inst.parent
}

// SetParent sets the parent basic block of the instruction.
func (inst *InstLShR) SetParent(parent *BasicBlock) {
	inst.parent = parent
}

// X returns the x operand of the lshr instruction.
func (inst *InstLShR) X() value.Value {
	return inst.x
}

// Y returns the y operand of the lshr instruction.
func (inst *InstLShR) Y() value.Value {
	return inst.y
}

// --- [ ashr ] ----------------------------------------------------------------

// InstAShR represents an arithmetic shift right instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#ashr-instruction
type InstAShR struct {
	// Parent basic block.
	parent *BasicBlock
	// Identifier associated with the instruction.
	ident string
	// Operands.
	x, y value.Value
}

// NewAShR returns a new ashr instruction based on the given operands.
func NewAShR(x, y value.Value) *InstAShR {
	return &InstAShR{x: x, y: y}
}

// Type returns the type of the instruction.
func (inst *InstAShR) Type() types.Type {
	return inst.x.Type()
}

// Ident returns the identifier associated with the instruction.
func (inst *InstAShR) Ident() string {
	return enc.Local(inst.ident)
}

// SetIdent sets the identifier associated with the instruction.
func (inst *InstAShR) SetIdent(ident string) {
	inst.ident = ident
}

// LLVMString returns the LLVM syntax representation of the instruction.
func (inst *InstAShR) LLVMString() string {
	return fmt.Sprintf("%s = ashr %s %s, %s",
		inst.Ident(),
		inst.Type().LLVMString(),
		inst.x.Ident(),
		inst.y.Ident())
}

// Parent returns the parent basic block of the instruction.
func (inst *InstAShR) Parent() *BasicBlock {
	return inst.parent
}

// SetParent sets the parent basic block of the instruction.
func (inst *InstAShR) SetParent(parent *BasicBlock) {
	inst.parent = parent
}

// X returns the x operand of the ashr instruction.
func (inst *InstAShR) X() value.Value {
	return inst.x
}

// Y returns the y operand of the ashr instruction.
func (inst *InstAShR) Y() value.Value {
	return inst.y
}

// --- [ and ] -----------------------------------------------------------------

// InstAnd represents an AND instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#and-instruction
type InstAnd struct {
	// Parent basic block.
	parent *BasicBlock
	// Identifier associated with the instruction.
	ident string
	// Operands.
	x, y value.Value
}

// NewAnd returns a new and instruction based on the given operands.
func NewAnd(x, y value.Value) *InstAnd {
	return &InstAnd{x: x, y: y}
}

// Type returns the type of the instruction.
func (inst *InstAnd) Type() types.Type {
	return inst.x.Type()
}

// Ident returns the identifier associated with the instruction.
func (inst *InstAnd) Ident() string {
	return enc.Local(inst.ident)
}

// SetIdent sets the identifier associated with the instruction.
func (inst *InstAnd) SetIdent(ident string) {
	inst.ident = ident
}

// LLVMString returns the LLVM syntax representation of the instruction.
func (inst *InstAnd) LLVMString() string {
	return fmt.Sprintf("%s = and %s %s, %s",
		inst.Ident(),
		inst.Type().LLVMString(),
		inst.x.Ident(),
		inst.y.Ident())
}

// Parent returns the parent basic block of the instruction.
func (inst *InstAnd) Parent() *BasicBlock {
	return inst.parent
}

// SetParent sets the parent basic block of the instruction.
func (inst *InstAnd) SetParent(parent *BasicBlock) {
	inst.parent = parent
}

// X returns the x operand of the and instruction.
func (inst *InstAnd) X() value.Value {
	return inst.x
}

// Y returns the y operand of the and instruction.
func (inst *InstAnd) Y() value.Value {
	return inst.y
}

// --- [ or ] ------------------------------------------------------------------

// InstOr represents an OR instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#or-instruction
type InstOr struct {
	// Parent basic block.
	parent *BasicBlock
	// Identifier associated with the instruction.
	ident string
	// Operands.
	x, y value.Value
}

// NewOr returns a new or instruction based on the given operands.
func NewOr(x, y value.Value) *InstOr {
	return &InstOr{x: x, y: y}
}

// Type returns the type of the instruction.
func (inst *InstOr) Type() types.Type {
	return inst.x.Type()
}

// Ident returns the identifier associated with the instruction.
func (inst *InstOr) Ident() string {
	return enc.Local(inst.ident)
}

// SetIdent sets the identifier associated with the instruction.
func (inst *InstOr) SetIdent(ident string) {
	inst.ident = ident
}

// LLVMString returns the LLVM syntax representation of the instruction.
func (inst *InstOr) LLVMString() string {
	return fmt.Sprintf("%s = or %s %s, %s",
		inst.Ident(),
		inst.Type().LLVMString(),
		inst.x.Ident(),
		inst.y.Ident())
}

// Parent returns the parent basic block of the instruction.
func (inst *InstOr) Parent() *BasicBlock {
	return inst.parent
}

// SetParent sets the parent basic block of the instruction.
func (inst *InstOr) SetParent(parent *BasicBlock) {
	inst.parent = parent
}

// X returns the x operand of the or instruction.
func (inst *InstOr) X() value.Value {
	return inst.x
}

// Y returns the y operand of the or instruction.
func (inst *InstOr) Y() value.Value {
	return inst.y
}

// --- [ xor ] -----------------------------------------------------------------

// InstXor represents an exclusive-OR instruction.
//
// References:
//    http://llvm.org/docs/LangRef.html#xor-instruction
type InstXor struct {
	// Parent basic block.
	parent *BasicBlock
	// Identifier associated with the instruction.
	ident string
	// Operands.
	x, y value.Value
}

// NewXor returns a new xor instruction based on the given operands.
func NewXor(x, y value.Value) *InstXor {
	return &InstXor{x: x, y: y}
}

// Type returns the type of the instruction.
func (inst *InstXor) Type() types.Type {
	return inst.x.Type()
}

// Ident returns the identifier associated with the instruction.
func (inst *InstXor) Ident() string {
	return enc.Local(inst.ident)
}

// SetIdent sets the identifier associated with the instruction.
func (inst *InstXor) SetIdent(ident string) {
	inst.ident = ident
}

// LLVMString returns the LLVM syntax representation of the instruction.
func (inst *InstXor) LLVMString() string {
	return fmt.Sprintf("%s = xor %s %s, %s",
		inst.Ident(),
		inst.Type().LLVMString(),
		inst.x.Ident(),
		inst.y.Ident())
}

// Parent returns the parent basic block of the instruction.
func (inst *InstXor) Parent() *BasicBlock {
	return inst.parent
}

// SetParent sets the parent basic block of the instruction.
func (inst *InstXor) SetParent(parent *BasicBlock) {
	inst.parent = parent
}

// X returns the x operand of the xor instruction.
func (inst *InstXor) X() value.Value {
	return inst.x
}

// Y returns the y operand of the xor instruction.
func (inst *InstXor) Y() value.Value {
	return inst.y
}
