package ir

// Assert that each instruction implements the ir.Instruction interface.
var (
	// Binary instructions.
	_ Instruction = (*InstAdd)(nil)
	_ Instruction = (*InstFAdd)(nil)
	_ Instruction = (*InstSub)(nil)
	_ Instruction = (*InstFSub)(nil)
	_ Instruction = (*InstMul)(nil)
	_ Instruction = (*InstFMul)(nil)
	_ Instruction = (*InstUDiv)(nil)
	_ Instruction = (*InstSDiv)(nil)
	_ Instruction = (*InstFDiv)(nil)
	_ Instruction = (*InstURem)(nil)
	_ Instruction = (*InstSRem)(nil)
	_ Instruction = (*InstFRem)(nil)
	// Bitwise instructions.
	_ Instruction = (*InstShl)(nil)
	_ Instruction = (*InstLShr)(nil)
	_ Instruction = (*InstAShr)(nil)
	_ Instruction = (*InstAnd)(nil)
	_ Instruction = (*InstOr)(nil)
	_ Instruction = (*InstXor)(nil)
	// Vector instructions.
	_ Instruction = (*InstExtractElement)(nil)
	_ Instruction = (*InstInsertElement)(nil)
	_ Instruction = (*InstShuffleVector)(nil)
	// Aggregate instructions.
	_ Instruction = (*InstExtractValue)(nil)
	_ Instruction = (*InstInsertValue)(nil)
	// Memory instructions.
	_ Instruction = (*InstAlloca)(nil)
	_ Instruction = (*InstLoad)(nil)
	_ Instruction = (*InstStore)(nil)
	_ Instruction = (*InstFence)(nil)
	_ Instruction = (*InstCmpXchg)(nil)
	_ Instruction = (*InstAtomicRMW)(nil)
	_ Instruction = (*InstGetElementPtr)(nil)
	// Conversion instructions.
	_ Instruction = (*InstTrunc)(nil)
	_ Instruction = (*InstZExt)(nil)
	_ Instruction = (*InstSExt)(nil)
	_ Instruction = (*InstFPTrunc)(nil)
	_ Instruction = (*InstFPExt)(nil)
	_ Instruction = (*InstFPToUI)(nil)
	_ Instruction = (*InstFPToSI)(nil)
	_ Instruction = (*InstUIToFP)(nil)
	_ Instruction = (*InstSIToFP)(nil)
	_ Instruction = (*InstPtrToInt)(nil)
	_ Instruction = (*InstIntToPtr)(nil)
	_ Instruction = (*InstBitCast)(nil)
	_ Instruction = (*InstAddrSpaceCast)(nil)
	// Other instructions.
	_ Instruction = (*InstICmp)(nil)
	_ Instruction = (*InstFCmp)(nil)
	_ Instruction = (*InstPhi)(nil)
	_ Instruction = (*InstSelect)(nil)
	_ Instruction = (*InstCall)(nil)
	_ Instruction = (*InstVAArg)(nil)
	_ Instruction = (*InstLandingPad)(nil)
	_ Instruction = (*InstCatchPad)(nil)
	_ Instruction = (*InstCleanupPad)(nil)
)

// Assert that each terminator implements the ir.Terminator interface.
var (
	// Terminators.
	_ Terminator = (*TermRet)(nil)
	_ Terminator = (*TermBr)(nil)
	_ Terminator = (*TermCondBr)(nil)
	_ Terminator = (*TermSwitch)(nil)
	_ Terminator = (*TermIndirectBr)(nil)
	_ Terminator = (*TermInvoke)(nil)
	_ Terminator = (*TermResume)(nil)
	_ Terminator = (*TermCatchSwitch)(nil)
	_ Terminator = (*TermCatchRet)(nil)
	_ Terminator = (*TermCleanupRet)(nil)
	_ Terminator = (*TermUnreachable)(nil)
)
