// Code generated by "string2enum -linecomment -type AtomicOrdering /home/u/Desktop/go/src/github.com/llir/llvm/ir/enum"; DO NOT EDIT.

package enum

import "fmt"
import "github.com/llir/llvm/ir/enum"

const _AtomicOrdering_name = "noneacq_relacquiremonotonicreleaseseq_cstunordered"

var _AtomicOrdering_index = [...]uint8{0, 4, 11, 18, 27, 34, 41, 50}

func AtomicOrderingFromString(s string) enum.AtomicOrdering {
	if len(s) == 0 {
		return 0
	}
	for i := range _AtomicOrdering_index[:len(_AtomicOrdering_index)-1] {
		if s == _AtomicOrdering_name[_AtomicOrdering_index[i]:_AtomicOrdering_index[i+1]] {
			return enum.AtomicOrdering(i)
		}
	}
	panic(fmt.Errorf("unable to locate AtomicOrdering enum corresponding to %q", s))
}
