// Code generated by "string2enum -linecomment -type AtomicOp ../../ir/enum"; DO NOT EDIT.

package enum

import "fmt"
import "github.com/llir/llvm/ir/enum"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the string2enum command to generate them again.
	var x [1]struct{}
	_ = x[enum.AtomicOpAdd-1]
	_ = x[enum.AtomicOpAnd-2]
	_ = x[enum.AtomicOpFAdd-3]
	_ = x[enum.AtomicOpFSub-4]
	_ = x[enum.AtomicOpMax-5]
	_ = x[enum.AtomicOpMin-6]
	_ = x[enum.AtomicOpNAnd-7]
	_ = x[enum.AtomicOpOr-8]
	_ = x[enum.AtomicOpSub-9]
	_ = x[enum.AtomicOpUMax-10]
	_ = x[enum.AtomicOpUMin-11]
	_ = x[enum.AtomicOpXChg-12]
	_ = x[enum.AtomicOpXor-13]
}

const _AtomicOp_name = "addandfaddfsubmaxminnandorsubumaxuminxchgxor"

var _AtomicOp_index = [...]uint8{0, 3, 6, 10, 14, 17, 20, 24, 26, 29, 33, 37, 41, 44}

// AtomicOpFromString returns the AtomicOp enum corresponding to s.
func AtomicOpFromString(s string) enum.AtomicOp {
	if len(s) == 0 {
		return 0
	}
	for i := range _AtomicOp_index[:len(_AtomicOp_index)-1] {
		if s == _AtomicOp_name[_AtomicOp_index[i]:_AtomicOp_index[i+1]] {
			return enum.AtomicOp(i + 1)
		}
	}
	panic(fmt.Errorf("unable to locate AtomicOp enum corresponding to %q", s))
}
