// Code generated by "string2enum -linecomment -type ClauseType /home/u/Desktop/go/src/github.com/llir/llvm/ir/enum"; DO NOT EDIT.

package enum

import "fmt"
import "github.com/llir/llvm/ir/enum"

const _ClauseType_name = "catchfilter"

var _ClauseType_index = [...]uint8{0, 5, 11}

func ClauseTypeFromString(s string) enum.ClauseType {
	if len(s) == 0 {
		return 0
	}
	for i := range _ClauseType_index[:len(_ClauseType_index)-1] {
		if s == _ClauseType_name[_ClauseType_index[i]:_ClauseType_index[i+1]] {
			return enum.ClauseType(i + 1)
		}
	}
	panic(fmt.Errorf("unable to locate ClauseType enum corresponding to %q", s))
}
