// Code generated by "string2enum -linecomment -type DIFlag ../../ir/enum"; DO NOT EDIT.

package enum

import (
	"fmt"

	"github.com/llir/llvm/ir/enum"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the string2enum command to generate them again.
	var x [1]struct{}
	_ = x[enum.DIFlagZero-0]
	_ = x[enum.DIFlagPrivate-1]
	_ = x[enum.DIFlagProtected-2]
	_ = x[enum.DIFlagPublic-3]
	_ = x[enum.DIFlagFwdDecl-4]
	_ = x[enum.DIFlagAppleBlock-8]
	_ = x[enum.DIFlagReservedBit4-16]
	_ = x[enum.DIFlagVirtual-32]
	_ = x[enum.DIFlagArtificial-64]
	_ = x[enum.DIFlagExplicit-128]
	_ = x[enum.DIFlagPrototyped-256]
	_ = x[enum.DIFlagObjcClassComplete-512]
	_ = x[enum.DIFlagObjectPointer-1024]
	_ = x[enum.DIFlagVector-2048]
	_ = x[enum.DIFlagStaticMember-4096]
	_ = x[enum.DIFlagLValueReference-8192]
	_ = x[enum.DIFlagRValueReference-16384]
	_ = x[enum.DIFlagExportSymbols-32768]
	_ = x[enum.DIFlagSingleInheritance-65536]
	_ = x[enum.DIFlagMultipleInheritance-131072]
	_ = x[enum.DIFlagVirtualInheritance-196608]
	_ = x[enum.DIFlagIntroducedVirtual-262144]
	_ = x[enum.DIFlagBitField-524288]
	_ = x[enum.DIFlagNoReturn-1048576]
	_ = x[enum.DIFlagTypePassByValue-4194304]
	_ = x[enum.DIFlagTypePassByReference-8388608]
	_ = x[enum.DIFlagEnumClass-16777216]
	_ = x[enum.DIFlagThunk-33554432]
	_ = x[enum.DIFlagNonTrivial-67108864]
	_ = x[enum.DIFlagBigEndian-134217728]
	_ = x[enum.DIFlagLittleEndian-268435456]
	_ = x[enum.DIFlagAllCallsDescribed-536870912]
	_ = x[enum.DIFlagIndirectVirtualBase-36]
	_ = x[enum.DIFlagAccessibility-3]
	_ = x[enum.DIFlagPtrToMemberRep-196608]
}

const _DIFlag_name = "DIFlagZeroDIFlagPrivateDIFlagProtectedDIFlagPublicDIFlagFwdDeclDIFlagAppleBlockDIFlagReservedBit4DIFlagVirtualDIFlagIndirectVirtualBaseDIFlagArtificialDIFlagExplicitDIFlagPrototypedDIFlagObjcClassCompleteDIFlagObjectPointerDIFlagVectorDIFlagStaticMemberDIFlagLValueReferenceDIFlagRValueReferenceDIFlagExportSymbolsDIFlagSingleInheritanceDIFlagMultipleInheritanceDIFlagVirtualInheritanceDIFlagIntroducedVirtualDIFlagBitFieldDIFlagNoReturnDIFlagTypePassByValueDIFlagTypePassByReferenceDIFlagEnumClassDIFlagThunkDIFlagNonTrivialDIFlagBigEndianDIFlagLittleEndianDIFlagAllCallsDescribed"

var _DIFlag_map = map[enum.DIFlag]string{
	0:         _DIFlag_name[0:10],
	1:         _DIFlag_name[10:23],
	2:         _DIFlag_name[23:38],
	3:         _DIFlag_name[38:50],
	4:         _DIFlag_name[50:63],
	8:         _DIFlag_name[63:79],
	16:        _DIFlag_name[79:97],
	32:        _DIFlag_name[97:110],
	36:        _DIFlag_name[110:135],
	64:        _DIFlag_name[135:151],
	128:       _DIFlag_name[151:165],
	256:       _DIFlag_name[165:181],
	512:       _DIFlag_name[181:204],
	1024:      _DIFlag_name[204:223],
	2048:      _DIFlag_name[223:235],
	4096:      _DIFlag_name[235:253],
	8192:      _DIFlag_name[253:274],
	16384:     _DIFlag_name[274:295],
	32768:     _DIFlag_name[295:314],
	65536:     _DIFlag_name[314:337],
	131072:    _DIFlag_name[337:362],
	196608:    _DIFlag_name[362:386],
	262144:    _DIFlag_name[386:409],
	524288:    _DIFlag_name[409:423],
	1048576:   _DIFlag_name[423:437],
	4194304:   _DIFlag_name[437:458],
	8388608:   _DIFlag_name[458:483],
	16777216:  _DIFlag_name[483:498],
	33554432:  _DIFlag_name[498:509],
	67108864:  _DIFlag_name[509:525],
	134217728: _DIFlag_name[525:540],
	268435456: _DIFlag_name[540:558],
	536870912: _DIFlag_name[558:581],
}

// DIFlagFromString returns the DIFlag enum corresponding to s.
func DIFlagFromString(s string) enum.DIFlag {
	for key, val := range _DIFlag_map {
		if s == val {
			return key
		}
	}
	panic(fmt.Errorf("unable to locate DIFlag enum corresponding to %q", s))
}
