// Code generated by "string2enum -linecomment -type DwarfVirtuality /home/u/Desktop/go/src/github.com/llir/llvm/ir/enum"; DO NOT EDIT.

package enum

import "fmt"
import "github.com/llir/llvm/ir/enum"

const _DwarfVirtuality_name = "DW_VIRTUALITY_noneDW_VIRTUALITY_virtualDW_VIRTUALITY_pure_virtual"

var _DwarfVirtuality_index = [...]uint8{0, 18, 39, 65}

func DwarfVirtualityFromString(s string) enum.DwarfVirtuality {
	if len(s) == 0 {
		return 0
	}
	for i := range _DwarfVirtuality_index[:len(_DwarfVirtuality_index)-1] {
		if s == _DwarfVirtuality_name[_DwarfVirtuality_index[i]:_DwarfVirtuality_index[i+1]] {
			return enum.DwarfVirtuality(i)
		}
	}
	panic(fmt.Errorf("unable to locate DwarfVirtuality enum corresponding to %q", s))
}
