// Code generated by "string2enum -linecomment -type DwarfCC ../../ir/enum"; DO NOT EDIT.

package enum

import (
	"fmt"

	"github.com/llir/llvm/ir/enum"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the string2enum command to generate them again.
	var x [1]struct{}
	_ = x[enum.DwarfCCNormal-1]
	_ = x[enum.DwarfCCProgram-2]
	_ = x[enum.DwarfCCNoCall-3]
	_ = x[enum.DwarfCCPassByReference-4]
	_ = x[enum.DwarfCCPassByValue-5]
	_ = x[enum.DwarfCCGNUBorlandFastcallI386-65]
	_ = x[enum.DwarfCCBORLANDSafecall-176]
	_ = x[enum.DwarfCCBORLANDStdcall-177]
	_ = x[enum.DwarfCCBORLANDPascal-178]
	_ = x[enum.DwarfCCBORLANDMSFastcall-179]
	_ = x[enum.DwarfCCBORLANDMSReturn-180]
	_ = x[enum.DwarfCCBORLANDThiscall-181]
	_ = x[enum.DwarfCCBORLANDFastcall-182]
	_ = x[enum.DwarfCCLLVMVectorcall-192]
}

const (
	_DwarfCC_name_0 = "DW_CC_normalDW_CC_programDW_CC_nocallDW_CC_pass_by_referenceDW_CC_pass_by_value"
	_DwarfCC_name_1 = "DW_CC_GNU_borland_fastcall_i386"
	_DwarfCC_name_2 = "DW_CC_BORLAND_safecallDW_CC_BORLAND_stdcallDW_CC_BORLAND_pascalDW_CC_BORLAND_msfastcallDW_CC_BORLAND_msreturnDW_CC_BORLAND_thiscallDW_CC_BORLAND_fastcall"
	_DwarfCC_name_3 = "DW_CC_LLVM_vectorcall"
)

var (
	_DwarfCC_index_0 = [...]uint8{0, 12, 25, 37, 60, 79}
	_DwarfCC_index_2 = [...]uint8{0, 22, 43, 63, 87, 109, 131, 153}
)

// DwarfCCFromString returns the DwarfCC enum corresponding to s.
func DwarfCCFromString(s string) enum.DwarfCC {
	if len(s) == 0 {
		return 0
	}
	for i := range _DwarfCC_index_0[:len(_DwarfCC_index_0)-1] {
		if s == _DwarfCC_name_0[_DwarfCC_index_0[i]:_DwarfCC_index_0[i+1]] {
			return enum.DwarfCC(i + 1)
		}
	}
	if s == _DwarfCC_name_1 {
		return enum.DwarfCC(65)
	}
	for i := range _DwarfCC_index_2[:len(_DwarfCC_index_2)-1] {
		if s == _DwarfCC_name_2[_DwarfCC_index_2[i]:_DwarfCC_index_2[i+1]] {
			return enum.DwarfCC(i + 176)
		}
	}
	if s == _DwarfCC_name_3 {
		return enum.DwarfCC(192)
	}
	panic(fmt.Errorf("unable to locate DwarfCC enum corresponding to %q", s))
}

func _(s string) {
	// Check for duplicate string values in type "DwarfCC".
	switch s {
	// 1
	case "DW_CC_normal":
	// 2
	case "DW_CC_program":
	// 3
	case "DW_CC_nocall":
	// 4
	case "DW_CC_pass_by_reference":
	// 5
	case "DW_CC_pass_by_value":
	// 65
	case "DW_CC_GNU_borland_fastcall_i386":
	// 176
	case "DW_CC_BORLAND_safecall":
	// 177
	case "DW_CC_BORLAND_stdcall":
	// 178
	case "DW_CC_BORLAND_pascal":
	// 179
	case "DW_CC_BORLAND_msfastcall":
	// 180
	case "DW_CC_BORLAND_msreturn":
	// 181
	case "DW_CC_BORLAND_thiscall":
	// 182
	case "DW_CC_BORLAND_fastcall":
	// 192
	case "DW_CC_LLVM_vectorcall":
	}
}
