// Code generated by "string2enum -linecomment -type FastMathFlag /home/u/Desktop/go/src/github.com/llir/llvm/ir/enum"; DO NOT EDIT.

package enum

import "fmt"
import "github.com/llir/llvm/ir/enum"

const _FastMathFlag_name = "afnarcpcontractfastninfnnannszreassoc"

var _FastMathFlag_index = [...]uint8{0, 3, 7, 15, 19, 23, 27, 30, 37}

func FastMathFlagFromString(s string) enum.FastMathFlag {
	if len(s) == 0 {
		return 0
	}
	for i := range _FastMathFlag_index[:len(_FastMathFlag_index)-1] {
		if s == _FastMathFlag_name[_FastMathFlag_index[i]:_FastMathFlag_index[i+1]] {
			return enum.FastMathFlag(i)
		}
	}
	panic(fmt.Errorf("unable to locate FastMathFlag enum corresponding to %q", s))
}
