// Code generated by "string2enum -linecomment -type FloatKind -pkg enum /home/u/Desktop/go/src/github.com/llir/llvm/ir/types"; DO NOT EDIT.

package enum

import "fmt"
import "github.com/llir/llvm/ir/types"

const _FloatKind_name = "halffloatdoublefp128x86_fp80ppc_fp128"

var _FloatKind_index = [...]uint8{0, 4, 9, 15, 20, 28, 37}

func FloatKindFromString(s string) types.FloatKind {
	if len(s) == 0 {
		return 0
	}
	for i := range _FloatKind_index[:len(_FloatKind_index)-1] {
		if s == _FloatKind_name[_FloatKind_index[i]:_FloatKind_index[i+1]] {
			return types.FloatKind(i)
		}
	}
	panic(fmt.Errorf("unable to locate FloatKind enum corresponding to %q", s))
}
