// Code generated by "string2enum -linecomment -type FuncAttr ../../ir/enum"; DO NOT EDIT.

package enum

import (
	"fmt"

	"github.com/llir/llvm/ir/enum"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the string2enum command to generate them again.
	var x [1]struct{}
	_ = x[enum.FuncAttrAlwaysInline-0]
	_ = x[enum.FuncAttrArgMemOnly-1]
	_ = x[enum.FuncAttrBuiltin-2]
	_ = x[enum.FuncAttrCold-3]
	_ = x[enum.FuncAttrConvergent-4]
	_ = x[enum.FuncAttrInaccessibleMemOnly-5]
	_ = x[enum.FuncAttrInaccessibleMemOrArgMemOnly-6]
	_ = x[enum.FuncAttrInlineHint-7]
	_ = x[enum.FuncAttrJumpTable-8]
	_ = x[enum.FuncAttrMinSize-9]
	_ = x[enum.FuncAttrNaked-10]
	_ = x[enum.FuncAttrNoBuiltin-11]
	_ = x[enum.FuncAttrNoCFCheck-12]
	_ = x[enum.FuncAttrNoDuplicate-13]
	_ = x[enum.FuncAttrNoFree-14]
	_ = x[enum.FuncAttrNoImplicitFloat-15]
	_ = x[enum.FuncAttrNoInline-16]
	_ = x[enum.FuncAttrNoMerge-17]
	_ = x[enum.FuncAttrNonLazyBind-18]
	_ = x[enum.FuncAttrNoRecurse-19]
	_ = x[enum.FuncAttrNoRedZone-20]
	_ = x[enum.FuncAttrNoReturn-21]
	_ = x[enum.FuncAttrNoSync-22]
	_ = x[enum.FuncAttrNoUnwind-23]
	_ = x[enum.FuncAttrNullPointerIsValid-24]
	_ = x[enum.FuncAttrOptForFuzzing-25]
	_ = x[enum.FuncAttrOptNone-26]
	_ = x[enum.FuncAttrOptSize-27]
	_ = x[enum.FuncAttrReadNone-28]
	_ = x[enum.FuncAttrReadOnly-29]
	_ = x[enum.FuncAttrReturnsTwice-30]
	_ = x[enum.FuncAttrSafeStack-31]
	_ = x[enum.FuncAttrSanitizeAddress-32]
	_ = x[enum.FuncAttrSanitizeHWAddress-33]
	_ = x[enum.FuncAttrSanitizeMemory-34]
	_ = x[enum.FuncAttrSanitizeMemTag-35]
	_ = x[enum.FuncAttrSanitizeThread-36]
	_ = x[enum.FuncAttrShadowCallStack-37]
	_ = x[enum.FuncAttrSpeculatable-38]
	_ = x[enum.FuncAttrSpeculativeLoadHardening-39]
	_ = x[enum.FuncAttrSSP-40]
	_ = x[enum.FuncAttrSSPReq-41]
	_ = x[enum.FuncAttrSSPStrong-42]
	_ = x[enum.FuncAttrStrictFP-43]
	_ = x[enum.FuncAttrUwtable-44]
	_ = x[enum.FuncAttrWillReturn-45]
	_ = x[enum.FuncAttrWriteOnly-46]
}

const _FuncAttr_name = "alwaysinlineargmemonlybuiltincoldconvergentinaccessiblememonlyinaccessiblemem_or_argmemonlyinlinehintjumptableminsizenakednobuiltinnocf_checknoduplicatenofreenoimplicitfloatnoinlinenomergenonlazybindnorecursenoredzonenoreturnnosyncnounwindnull_pointer_is_validoptforfuzzingoptnoneoptsizereadnonereadonlyreturns_twicesafestacksanitize_addresssanitize_hwaddresssanitize_memorysanitize_memtagsanitize_threadshadowcallstackspeculatablespeculative_load_hardeningsspsspreqsspstrongstrictfpuwtablewillreturnwriteonly"

var _FuncAttr_index = [...]uint16{0, 12, 22, 29, 33, 43, 62, 91, 101, 110, 117, 122, 131, 141, 152, 158, 173, 181, 188, 199, 208, 217, 225, 231, 239, 260, 273, 280, 287, 295, 303, 316, 325, 341, 359, 374, 389, 404, 419, 431, 457, 460, 466, 475, 483, 490, 500, 509}

// FuncAttrFromString returns the FuncAttr enum corresponding to s.
func FuncAttrFromString(s string) enum.FuncAttr {
	if len(s) == 0 {
		return 0
	}
	for i := range _FuncAttr_index[:len(_FuncAttr_index)-1] {
		if s == _FuncAttr_name[_FuncAttr_index[i]:_FuncAttr_index[i+1]] {
			return enum.FuncAttr(i)
		}
	}
	panic(fmt.Errorf("unable to locate FuncAttr enum corresponding to %q", s))
}

func _(s string) {
	// Check for duplicate string values in type "FuncAttr".
	switch s {
	// 0
	case "alwaysinline":
	// 1
	case "argmemonly":
	// 2
	case "builtin":
	// 3
	case "cold":
	// 4
	case "convergent":
	// 5
	case "inaccessiblememonly":
	// 6
	case "inaccessiblemem_or_argmemonly":
	// 7
	case "inlinehint":
	// 8
	case "jumptable":
	// 9
	case "minsize":
	// 10
	case "naked":
	// 11
	case "nobuiltin":
	// 12
	case "nocf_check":
	// 13
	case "noduplicate":
	// 14
	case "nofree":
	// 15
	case "noimplicitfloat":
	// 16
	case "noinline":
	// 17
	case "nomerge":
	// 18
	case "nonlazybind":
	// 19
	case "norecurse":
	// 20
	case "noredzone":
	// 21
	case "noreturn":
	// 22
	case "nosync":
	// 23
	case "nounwind":
	// 24
	case "null_pointer_is_valid":
	// 25
	case "optforfuzzing":
	// 26
	case "optnone":
	// 27
	case "optsize":
	// 28
	case "readnone":
	// 29
	case "readonly":
	// 30
	case "returns_twice":
	// 31
	case "safestack":
	// 32
	case "sanitize_address":
	// 33
	case "sanitize_hwaddress":
	// 34
	case "sanitize_memory":
	// 35
	case "sanitize_memtag":
	// 36
	case "sanitize_thread":
	// 37
	case "shadowcallstack":
	// 38
	case "speculatable":
	// 39
	case "speculative_load_hardening":
	// 40
	case "ssp":
	// 41
	case "sspreq":
	// 42
	case "sspstrong":
	// 43
	case "strictfp":
	// 44
	case "uwtable":
	// 45
	case "willreturn":
	// 46
	case "writeonly":
	}
}
