all:
	string2enum -linecomment -type AtomicOrdering /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type CallingConv /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type DLLStorageClass /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type FastMathFlag /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type FPred /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type IPred /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type Linkage /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type OverflowFlag /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type Preemption /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type SelectionKind /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type Tail /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type TLSModel /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type UnnamedAddr /home/u/Desktop/go/src/github.com/llir/l/ir/enum
	string2enum -linecomment -type Visibility /home/u/Desktop/go/src/github.com/llir/l/ir/enum
