// Code generated by "string2enum -linecomment -type SelectionKind ../../ir/enum"; DO NOT EDIT.

package enum

import (
	"fmt"

	"github.com/llir/llvm/ir/enum"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the string2enum command to generate them again.
	var x [1]struct{}
	_ = x[enum.SelectionKindAny-0]
	_ = x[enum.SelectionKindExactMatch-1]
	_ = x[enum.SelectionKindLargest-2]
	_ = x[enum.SelectionKindNoDeduplicate-3]
	_ = x[enum.SelectionKindSameSize-4]
}

const _SelectionKind_name = "anyexactmatchlargestnodeduplicatesamesize"

var _SelectionKind_index = [...]uint8{0, 3, 13, 20, 33, 41}

// SelectionKindFromString returns the SelectionKind enum corresponding to s.
func SelectionKindFromString(s string) enum.SelectionKind {
	if len(s) == 0 {
		return 0
	}
	for i := range _SelectionKind_index[:len(_SelectionKind_index)-1] {
		if s == _SelectionKind_name[_SelectionKind_index[i]:_SelectionKind_index[i+1]] {
			return enum.SelectionKind(i)
		}
	}
	panic(fmt.Errorf("unable to locate SelectionKind enum corresponding to %q", s))
}

func _(s string) {
	// Check for duplicate string values in type "SelectionKind".
	switch s {
	// 0
	case "any":
	// 1
	case "exactmatch":
	// 2
	case "largest":
	// 3
	case "nodeduplicate":
	// 4
	case "samesize":
	}
}
