// Code generated by "stringer -linecomment -type FPred"; DO NOT EDIT.

package enum

import "strconv"

const _FPred_name = "falseoeqogeogtoleoltoneordtrueuequgeugtuleultuneuno"

var _FPred_index = [...]uint8{0, 5, 8, 11, 14, 17, 20, 23, 26, 30, 33, 36, 39, 42, 45, 48, 51}

func (i FPred) String() string {
	if i >= FPred(len(_FPred_index)-1) {
		return "FPred(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FPred_name[_FPred_index[i]:_FPred_index[i+1]]
}
